export { default as officeImg } from "./img/office-img.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as greenArrow } from "./img/green-arrow.svg"
export { default as gradientBg } from "./img/gradient-bg.png"
export { default as cardBg } from "./img/card-bg.png"
export { default as faqBg } from "./img/ermImg.png"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"
export { default as approved } from "./img/approved.svg"
export { default as policyIcon } from "./img/policyIcon.svg"

////new
export { default as motherCardImg } from "./img/motherCardImg.svg"
export { default as advanceAi } from "./img/advanceAi.webp"
export { default as receipt } from "./img/receipt.webp"
export { default as upi } from "./img/upi.webp"
export { default as walletExpense } from "./img/walletExpense.webp"

export { default as bannerLottie } from "./img/lottie/Expense.json"
export { default as itIcon } from "./img/it-saas-icon.svg"
export { default as ecoomerceIcon } from "./img/ecoomerce-icon.svg"
export { default as manufactureIcon } from "./img/manufacture-icon.svg"
export { default as logisticIcon } from "./img/logistic-icon.svg"
export { default as consultancyIcon } from "./img/consultancy.svg"
export { default as pharmacyIcon } from "./img/pharmacy.svg"
export { default as blurImg } from "./img/blurBg.png"


export { default as smartIconeOne } from "./img/smartIconOne.svg"
export { default as smartIconeTwo } from "./img/smartIconTwo.svg"
export { default as smartIconeThree } from "./img/smartIconThree.svg"

export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"
// export { default as stackCardThreeImg } from "./img/wide-acceptance-network.webp"
// export { default as stackCardsixImg } from "./img/wide-acceptance-network.webp"
export { default as stackCardThreeImg } from "./img/stack-card-three-img.webp"
export { default as stackCardsixImg } from "./img/stack-card-six-img.webp"

export { default as realTimeExpenseIcon } from "./img/real-time-icon.svg"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
// export { default as stackCardThreeIcon } from "./img/streamlined-reimbursement-icon.svg"
// export { default as stackCardsixIicon } from "./img/streamlined-reimbursement-icon.svg"
export { default as stackCardThreeIcon } from "./img/stack-card-three-icon.svg"
export { default as stackCardsixIicon } from "./img/stack-card-six-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
export { default as artboardBg} from "./img/ArtboardBg.svg"
