export { default as officeImg } from "./img/office-img.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as greenArrow } from "./img/green-arrow.svg"
export { default as gradientBg } from "./img/gradient-bg.png"
export { default as cardBg } from "./img/card-bg.png"
export { default as faqBg } from "./img/ermImg.png"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"
export { default as approved } from "./img/approved.svg"

export { default as motherCardImg } from "./img/motherCardImg.svg"
export { default as advanceAi } from "./img/advanceAi.webp"
export { default as receipt } from "./img/receipt.webp"
export { default as upi } from "./img/upi.webp"
export { default as walletExpense } from "./img/walletExpense.webp"

export { default as bannerLottie } from "./img/lottie/Expense.json"
export { default as itIcon } from "./img/it-saas-icon.svg"
export { default as ecoomerceIcon } from "./img/ecoomerce-icon.svg"
export { default as manufactureIcon } from "./img/manufacture-icon.svg"
export { default as logisticIcon } from "./img/logistic-icon.svg"
export { default as consultancyIcon } from "./img/consultancy.svg"
export { default as pharmacyIcon } from "./img/pharmacy.svg"
export { default as blurImg } from "./img/blurBg.png"

export { default as smartIconeOne } from "./img/smartIconOne.svg"
export { default as smartIconeTwo } from "./img/smartIconTwo.svg"
export { default as smartIconeThree } from "./img/smartIconThree.svg"

export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"

export { default as stackCardThreeImg } from "./img/stack-card-three-img.webp"
export { default as stackCardsixImg } from "./img/stack-card-six-img.webp"

export { default as realTimeExpenseIcon } from "./img/real-time-icon.svg"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as stackCardThreeIcon } from "./img/stack-card-three-icon.svg"
export { default as stackCardsixIicon } from "./img/stack-card-six-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
export { default as artboardBg } from "./img/ArtboardBg.svg"

export { default as whatsappIcon } from "./img/whatapp.svg"
export { default as mailIcon } from "./img/mail.svg"
export { default as scannIcon } from "./img/scanner.svg"
export { default as realTimeIcon } from "./img/realTime.svg"
export { default as travelIcon } from "./img/travel.svg"
export { default as autoCalculateIcon } from "./img/autoCalculate.svg"
export { default as awareIcon } from "./img/securty.svg"
export { default as integreatedControlIcon } from "./img/integreatedControl.svg"
export { default as walletlIcon } from "./img/wallet.svg"
export { default as controlIcon } from "./img/control.svg"
export { default as trackIcon } from "./img/track.svg"
export { default as cashIcon } from "./img/cash.svg"
export { default as taxSaveIcon } from "./img/taxSave.svg"
export { default as instantAcessIcon } from "./img/instantAcess.svg"
export { default as verifiedIcon } from "./img/verified.svg"
export { default as visibilityIcon } from "./img/visibility.svg"

export { default as corporateCard } from "./img/coprate-card.png"
export { default as automaticCard } from "./img/automaticCard.svg"
export { default as gstCard } from "./img/gst.png"
export { default as expenseCard } from "./img/expenseCard.svg"
export { default as exchangeCard } from "./img/exchangeCard.svg"
export { default as trackingCard } from "./img/tracking.svg"
export { default as disrubsmentCard } from "./img/disbruesment.svg"
export { default as customExpenseCard } from "./img/customExpense.svg"

export { default as encruption } from "./img/encruption.svg"
export { default as complience } from "./img/complienceIcon.svg"
export { default as audit } from "./img/auditIcon.svg"
export { default as signOn } from "./img/sign-on-icon.svg"
export { default as key } from "./img/key-icon.svg"
export { default as policyIcon } from "./img/policyIcon.svg"
export { default as bg1 } from "./img/bg4.jpg"
export { default as bg2 } from "./img/bg3.jpg"
export { default as bg3 } from "./img/bg2.jpg"
export { default as bg4 } from "./img/bg1.jpg"
export { default as bg5 } from "./img/bg6.jpg"
export { default as bg6 } from "./img/bg5.jpg"
