export { default as whiteArrow } from "./img/white-arrow.png"
export { default as blueArrow } from "./img/blue-arrrow.svg"

export { default as mealCardImg } from "./img/meal-card.png"
export { default as fuelCardImg } from "./img/fuel-card.svg"
export { default as termsAndConCardImg } from "./img/terms-and-conditon.png"
export { default as virtualCardImg } from "./img/virtual-card.svg"
export { default as digitalCardImg } from "./img/digital-marketing-card.svg"
export { default as sassCardImg } from "./img/sass-card.svg"
export { default as fleetCardImg } from "./img/fleet-card.svg"
export { default as payrollCarddImg } from "./img/payrollCard.webp"

export { default as heroCardImg } from "./img/hero card.webp"
export { default as mealCardImage } from "./img/meal-card.webp"
export { default as instantActionImg } from "./img/instant-action-img.webp"

export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"
export { default as integrationAudit } from "./img/integrated-audit.webp"
export { default as seemlessIntegration } from "./img/seemlessIntegration.webp"

export { default as realTimeExpenseIcon } from "./img/real-time-expense-icon.svg"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
export { default as integrationAuditIcon } from "./img/integrated-audit-icon.svg"
export { default as seemlessIntegrationIcon } from "./img/seemlessIntegration-icon.svg"
