import { StaticImageData } from "next/image"
import { Slide } from "@/components/sliderComponent/sliderComponent"

import amazonePrime from "./img/e-commerce/amazon-prime.webp"

import {
  ajio,
  amazonPrimeBg,
  amazonPrimeImg,
  amazonPrimeLogo,
  apolloBg,
  apolloImg,
  apolloLogo,
  blackberryLogo,
  cultfitBg,
  cultfitImg,
  cultfitLogo,
  dominosBg,
  dominosImg,
  dominosLogo,
  fancodeLogo,
  flipkart,
  fnp,
  healthkartLogo,
  imageFour,
  imageOne,
  imageThree,
  imageTwo,
  jockeyBg,
  jockeyImg,
  jockeyLogo,
  kfcLogo,
  levisBg,
  levisImg,
  levisLogo,
  macdonaldsBg,
  macdonaldsImg,
  macdonaldsLogo,
  mamaeathBg,
  mamaeathImg,
  mamaeathLogo,
  myglammBg,
  myglammImg,
  myglammLogo,
  nykaa,
  pantaloonBg,
  pantaloonImg,
  pantaloonLogo,
  pvrBg,
  pvrImg,
  pvrLogo,
  sliderFourBg,
  sliderOneBg,
  sliderThreeBg,
  sliderTwoBg,
  sonyLivBg,
  sonyLivImg,
  sonyLivLogo,
  swiggyBg,
  swiggyImg,
  swiggyLogo,
  westsideBg,
  westsideImg,
  westsideLogo,
  zee5Bg,
  zee5Img,
  zee5Logo,
  zomatoBg,
  zomatoImg,
  zomatoLogo,
} from "."
export type VoucherCard = {
  brandName: string | undefined
  titleHtml: string
  description: string
  discount: string
  cardImage: string | StaticImageData
  buttonUrl: string
}

// Example: slides, breadcrumbs, faq for each category
export const VOUCHER_DATA: Record<
  string,
  {
    title: string
    breadcrumbItems: { name: string; url: string }[]
    slides: Slide[]
    voucherCards: VoucherCard[]
  }
> = {
  "e-commerce-vouchers": {
    title: "E-commerce Vouchers",
    breadcrumbItems: [
      { name: "Home", url: "/" },
      { name: "Vouchers", url: "/products/vouchers" },
      { name: "E-commerce Vouchers", url: "/e-commerce-vouchers" },
    ],
    slides: [
      {
        heading: " Shop across a wide range of products with up to  ",
        subHeading:
          "Sit back and order from the comfort of your home with discounts. ",
        buttonText: "Buy Now",
        backgroundImage: sliderOneBg,
        rightImage: imageOne,
        brandName: "Amazon Prime Shopping Edition",
        buttonUrl: "/vouchers/amazon-prime-shopping",
        rightImageMaxHeight: "520px",
        discount: 0,
      },
      {
        heading:
          "Explore a world of products for every need, want, and wishlist ",
        subHeading: " Unlock extra value on every purchase with up to ",
        buttonText: "Buy Now",
        backgroundImage: sliderTwoBg,
        rightImage: imageTwo,
        brandName: "Flipkart Super Coins E-Gift Card",
        buttonUrl: "/vouchers/flipkart-super-coins",
        discount: 0,
      },
      {
        heading: "Showstopper beauty picks with up to ",
        subHeading:
          "Shop the best beauty and skincare products with great discounts. ",
        buttonText: "Buy Now",
        backgroundImage: sliderThreeBg,
        rightImage: imageThree,
        brandName: "Nykaa E-Gift Card",
        buttonUrl: "/vouchers/nykaa",
        discount: 0,
      },
      {
        heading: "Send your emotions as gifts with up to ",
        subHeading:
          "Make ordinary days special and special days memorable with great deals.",
        buttonText: "Buy Now",
        backgroundImage: sliderFourBg,
        rightImage: imageFour,
        brandName: "Ferns N Petals",
        buttonUrl: "/vouchers/fnp",
        discount: 0,
      },
    ],
    voucherCards: [
      {
        titleHtml: "Amazon Prime Shopping",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: amazonePrime,
        brandName: "Amazon Prime Shopping Edition",
        buttonUrl: "/vouchers/amazon-prime-shopping",
      },
      {
        titleHtml: "Nykaa",
        description: "E-Gift Card",
        discount: "0 %",
        cardImage: nykaa,
        brandName: "Nykaa E-Gift Card",
        buttonUrl: "/vouchers/nykaa",
      },
      {
        titleHtml: "Flipkart Supercoins",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: flipkart,
        brandName: "Flipkart Super Coins E-Gift Card",
        buttonUrl: "/vouchers/flipkart-super-coins",
      },
      {
        titleHtml: "Ajio",
        description: "Gift Card",
        discount: "0%",
        cardImage: ajio,
        brandName: "AJIO",
        buttonUrl: "/vouchers/ajio",
      },
      {
        titleHtml: "FNP",
        description: "Gift Card",
        discount: "0%",
        cardImage: fnp,
        brandName: "Ferns N Petals",
        buttonUrl: "/vouchers/fnp",
      },
    ],
    // faqData: VoucherFaqData["e-commerce-vouchers"].faqData,
  },

  "movie-and-music-vouchers": {
    title: "Movie & Music Vouchers",
    breadcrumbItems: [
      { name: "Home", url: "/" },
      { name: "Vouchers", url: "/products/vouchers" },
      { name: "Movie & Music Vouchers", url: "/movie-and-music-vouchers" },
    ],
    slides: [
      {
        heading: "Own every web series reference with up to ",
        subHeading: "Binging and saving go hand-in-hand with this voucher.",
        buttonText: "Buy Now",
        backgroundImage: amazonPrimeBg,
        rightImage: amazonPrimeImg,
        rightImageMarginTop: "-50px",
        brandName: "Amazon Prime Shopping Edition",
        buttonUrl: "/vouchers/amazon-prime",
        discount: 0,
      },
      {
        heading: "Popcorn ready? Binge with up to ",
        subHeading: "Your home. Your screen. Endless entertainment, anytime.",
        buttonText: "Buy Now",
        backgroundImage: sonyLivBg,
        rightImage: sonyLivImg,
        brandName: "SonyLIV Yearly",
        buttonUrl: "/vouchers/sony-liv",
        discount: 0,
      },
      {
        heading: "Watch the latest movies with up to ",
        subHeading: "Lights. Camera. Discount with this voucher.",
        buttonText: "Buy Now",
        backgroundImage: pvrBg,
        rightImage: pvrImg,
        brandName: "PVR",

        buttonUrl: "/vouchers/pvr",
        discount: 0,
      },
      {
        heading: "Entertainment in any language with up to ",
        subHeading:
          "From blockbuster movies and hit TV shows to originals – watch it all.",
        buttonText: "Buy Now",
        backgroundImage: zee5Bg,
        rightImage: zee5Img,
        brandName: "ZEE5",
        rightImageMaxHeight: "520px",
        rightImageMarginTop: "-80px",

        buttonUrl: "/vouchers/zee5",
        discount: 0,
      },
    ],
    voucherCards: [
      {
        titleHtml: "Amazon Prime",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: amazonPrimeLogo,
        buttonUrl: "/vouchers/amazon-prime",
        brandName: "Amazon Prime Shopping Edition",
      },
      {
        titleHtml: "SonyLiv Monthly",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: sonyLivLogo,
        buttonUrl: "/vouchers/sony-liv",
        brandName: "SonyLIV Yearly",
      },
      {
        titleHtml: "PVR ",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: pvrLogo,
        buttonUrl: "/vouchers/pvr",
        brandName: "PVR",
      },
      {
        titleHtml: "ZEE 5 ",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: zee5Logo,
        buttonUrl: "/vouchers/zee5",
        brandName: "ZEE5",
      },
      {
        titleHtml: "FanCode",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: fancodeLogo,
        buttonUrl: "/vouchers/fan-code",
        brandName: "Fancode B2B E-Gift Card",
      },
    ],
  },

  "apparels-vouchers": {
    title: "Apparels Vouchers",
    breadcrumbItems: [
      { name: "Home", url: "/" },
      { name: "Vouchers", url: "/products/vouchers" },
      { name: "Apparels Vouchers", url: "/apparels-vouchers" },
    ],
    slides: [
      {
        heading: "Everything fashion, home, & beauty with up to ",
        subHeading: "The place where your style meets its vibe.",
        buttonText: "Buy Now",
        backgroundImage: westsideBg,
        rightImage: westsideImg,
        rightImageMaxHeight: "520px",
        brandName: "Westside E-Gift Card",
        rightImageMarginTop: "-50px",
        buttonUrl: "/vouchers/westside",
        discount: 0,
      },
      {
        heading: "Iconic denims & modern fits with up to ",
        subHeading: "Own the streets with your fashion statement.",
        buttonText: "Buy Now",
        backgroundImage: levisBg,
        rightImage: levisImg,
        rightImageMaxHeight: "520px",
        brandName: "Levi's E-Gift Card",
        buttonUrl: "/vouchers/levis",
        discount: 0,
      },
      {
        heading: " Unmatched comfort fit with up to ",
        subHeading: "Everyday essentials that flex with you.",
        buttonText: "Buy Now",
        backgroundImage: jockeyBg,
        rightImage: jockeyImg,
        rightImageMaxHeight: "720px",
        brandName: "Jockey E-Gift Card",
        buttonUrl: "/vouchers/jockey",
        discount: 0,
      },
      {
        heading: "For all your moods & moments with up to ",
        subHeading: "Explore the vibrant mix of styles, trends, and colors.",
        buttonText: "Buy Now",
        backgroundImage: pantaloonBg,
        brandName: "Pantaloons E-Gift Card",
        rightImageMaxHeight: "520px",
        rightImage: pantaloonImg,
        buttonUrl: "/vouchers/pantaloons",
        discount: 0,
      },
    ],
    voucherCards: [
      {
        titleHtml: "Westside",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: westsideLogo,
        buttonUrl: "/vouchers/westside",
        brandName: "Westside E-Gift Card",
      },
      {
        titleHtml: "Levis",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: levisLogo,
        buttonUrl: "/vouchers/levis",
        brandName: "Levi's E-Gift Card",
      },
      {
        titleHtml: "Jockey",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: jockeyLogo,
        buttonUrl: "/vouchers/jockey",
        brandName: "Jockey E-Gift Card",
      },
      {
        titleHtml: "Pantaloons",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: pantaloonLogo,
        buttonUrl: "/vouchers/pantaloons",
        brandName: "Pantaloons E-Gift Card",
      },
      {
        titleHtml: "Blackberrys",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: blackberryLogo,
        buttonUrl: "/vouchers/blackberrys",
        brandName: "Blackberry E-Gift Card",
      },
    ],
  },
  "food-and-beverages-vouchers": {
    title: "Food and Beverages Vouchers",
    breadcrumbItems: [
      { name: "Home", url: "/" },
      { name: "Vouchers", url: "/products/vouchers" },
      {
        name: "Food and Beverages Vouchers",
        url: "/food-and-beverages-vouchers",
      },
    ],
    slides: [
      {
        heading: " Say yes to the large box of Friessssss with up to ",
        subHeading: "We bet you’ll love it more.",
        buttonText: "Buy Now",
        backgroundImage: macdonaldsBg,
        rightImage: macdonaldsImg,
        brandName: "McDonald’s Value Club Gift Voucher",
        rightImageMarginTop: "-50px",
        buttonUrl: "/vouchers/mcdonalds",
        discount: 0,
      },
      {
        heading: " Feel the cheeseeeee pull with up to ",
        subHeading: "Go bold with extra seasoning! ",
        buttonText: "Buy Now",
        backgroundImage: dominosBg,
        rightImage: dominosImg,
        brandName: "Dominos Pizza E-Gift Card",
        buttonUrl: "/vouchers/dominos",

        discount: 0,
      },
      {
        heading: "Cheat meals taste better with up to ",
        subHeading: "Binge eating is a talent not many own.",
        buttonText: "Buy Now",
        backgroundImage: swiggyBg,
        rightImage: swiggyImg,

        brandName: "Swiggy Money E-Gift Card",
        buttonUrl: "/vouchers/swiggy",
        discount: 0,
      },
      {
        heading: " Every meal made easy with up to ",
        subHeading: "When in doubt, food it out.",
        buttonText: "Buy Now",
        backgroundImage: zomatoBg,
        brandName: "Zomato E-Gift Voucher",
        rightImage: zomatoImg,
        rightImageMarginTop: "50px",
        buttonUrl: "/vouchers/zomato",
        discount: 0,
      },
    ],
    voucherCards: [
      {
        titleHtml: "McDonald’s",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: macdonaldsLogo,
        buttonUrl: "/vouchers/mcdonalds",
        brandName: "McDonald’s Value Club Gift Voucher",
      },
      {
        titleHtml: "Domino’s",
        description: "E‑Gift Card",
        discount: "0%",
        cardImage: dominosLogo,
        buttonUrl: "/vouchers/dominos",
        brandName: "Dominos Pizza E-Gift Card",
      },
      {
        titleHtml: "Swiggy",
        description: "Gift Card",
        discount: "0%",
        cardImage: swiggyLogo,
        buttonUrl: "/vouchers/swiggy",
        brandName: "Swiggy Money E-Gift Card",
      },
      {
        titleHtml: "Zomato ",
        description: "Gift Card",
        discount: "0%",
        cardImage: zomatoLogo,
        buttonUrl: "/vouchers/zomato",
        brandName: "Zomato E-Gift Voucher",
      },
      {
        titleHtml: "KFC",
        description: "Gift Card",
        discount: "0%",
        cardImage: kfcLogo,
        buttonUrl: "/vouchers/kfc",
        brandName: "KFC E-Gift Card",
      },
    ],
  },

  "health-and-wellness-vouchers": {
    title: "Health and Wellness Vouchers",
    breadcrumbItems: [
      { name: "Home", url: "/" },
      { name: "Vouchers", url: "/products/vouchers" },
      {
        name: "Health and Wellness Vouchers",
        url: "/health-and-wellness-vouchers",
      },
    ],
    slides: [
      {
        heading: "Safe & effective self-care products with up to ",
        subHeading:
          "Toxin-free skincare and haircare that loves you back, naturally.",
        buttonText: "Buy Now",
        backgroundImage: mamaeathBg,
        rightImage: mamaeathImg,
        rightImageMaxHeight: "588px",
        buttonUrl: "/vouchers/mamaearth",
        discount: 0,
        brandName: "Mamaearth",
      },
      {
        heading: "Health essentials delivered with up to ",
        subHeading:
          "Medicines, wellness, and healthcare delivered to your doorstep.",
        buttonText: "Buy Now",
        backgroundImage: apolloBg,
        rightImage: apolloImg,
        buttonUrl: "/vouchers/apollo",
        discount: 0,
        brandName: "Apollo Healing E-Gift Card",
      },
      {
        heading: "Start your fitness journey with up to ",
        subHeading: "Make fitness a part of your everyday life.",
        buttonText: "Buy Now",
        backgroundImage: cultfitBg,
        rightImage: cultfitImg,
        rightImageMaxHeight: "588px",
        buttonUrl: "/vouchers/cultfit",
        discount: 0,
        brandName: "Cultfit",
      },
      {
        heading: "Makeup that gets you with up to ",
        subHeading: "No drama. Just cruelty-free makeup.",
        buttonText: "Buy Now",
        backgroundImage: myglammBg,
        rightImage: myglammImg,
        buttonUrl: "/vouchers/myglamm",
        discount: 0,
        rightImageMaxHeight: "670px",
        brandName: "MyGlamm E-Gift Card",
      },
    ],
    voucherCards: [
      {
        titleHtml: "Mamaearth",
        description: "Gift Card",
        discount: "0%",
        cardImage: mamaeathLogo,
        buttonUrl: "/vouchers/mamaearth",
        brandName: "Mamaearth",
      },
      {
        titleHtml: "Apollo Pharmacy",
        description: " E-Gift Card",
        discount: "0%",
        cardImage: apolloLogo,
        buttonUrl: "/vouchers/apollo",
        brandName: "Apollo Healing E-Gift Card",
      },
      {
        titleHtml: "Cult Fit ",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: cultfitLogo,
        buttonUrl: "/vouchers/cultfit",
        brandName: "Cultfit",
      },
      {
        titleHtml: "MyGlamm",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: myglammLogo,
        buttonUrl: "/vouchers/myglamm",
        brandName: "MyGlamm E-Gift Card",
      },
      {
        titleHtml: "HealthKart ",
        description: "E-Gift Card",
        discount: "0%",
        cardImage: healthkartLogo,
        buttonUrl: "/vouchers/healthkart",
        brandName: "HealthKart",
      },
    ],
  },
}
