export { default as sliderOneBg } from "./img/e-commerce/sliderOneBg.webp"
export { default as sliderTwoBg } from "./img/e-commerce/sliderTwoBg.webp"
export { default as sliderThreeBg } from "./img/e-commerce/sliderThreeBg.webp"
export { default as sliderFourBg } from "./img/e-commerce/sliderFourBg.webp"

export { default as imageOne } from "./img/e-commerce/imageOne.webp"
export { default as imageTwo } from "./img/e-commerce/imageTwo.webp"
export { default as imageThree } from "./img/e-commerce/imageThree.webp"
export { default as imageFour } from "./img/e-commerce/imageFour.webp"
export { default as amazonePrime } from "./img/e-commerce/amazon-prime.webp"
export { default as flipkart } from "./img/e-commerce/flipkart.webp"
export { default as ajio } from "./img/e-commerce/ajio.webp"
export { default as fnp } from "./img/e-commerce/fnp.webp"
export { default as nykaa } from "./img/e-commerce/nykaa.webp"
