export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as digitalCardImg } from "./digital-marketing-card.svg"
export { default as fleetCardImg } from "./fleet-card.svg"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as fuelCardImg } from "./fuel-card.svg"
export { default as mealCardImg } from "./meal-card.png"
export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./real-time-expense-icon.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.png"
export { default as sassCardImg } from "./sass-card.svg"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
export { default as payrollCardImg } from "./payroll-card.webp"
export { default as mealCardImage } from "./meal-card.webp"
export { default as heroCardImg } from "./hero card.webp"
// Sliders
export { default as sliderOne } from "./sliderOne.svg"
export { default as sliderTwo } from "./sliderTwo.svg"
export { default as sliderThree } from "./sliderThree.svg"
export { default as sliderFour } from "./sliderFour.svg"
export { default as sliderFive } from "./sliderFive.svg"
// Icons
export { default as firstIcon } from "./icon-one.svg"
export { default as secondIcon } from "./icon-two.svg"
export { default as thirdIcon } from "./icon-three.svg"
export { default as fourthIcon } from "./icon-four.svg"
