export { default as whiteArrow } from "./img/white-arrow.png"
export { default as groupIcon } from "./img/groupIcon.png"
export { default as paymentSummary } from "./img/heroImg.webp"
export { default as blueArrow } from "./img/blue-arrrow.svg"

export { default as mealCardImage } from "./img/collect-payment.webp"
export { default as activationIcon } from "./img/activation.svg"
export { default as realTimeIcon } from "./img/real-time.svg"
export { default as PayoutIcon } from "./img/Layer_1.svg"

export { default as scrollIconOne } from "./img/scrollIconOne.svg"
export { default as scrollIconTwo } from "./img/scrollIconTwo.svg"
export { default as scrollIconThree } from "./img/scrollIconThree.svg"

export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"
export { default as stackCardSixImg } from "./img/stackCard-six-image.webp"

export { default as realTimeExpenseIcon } from "./img/real-time-icon.svg"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
export { default as stackCardSixIcon } from "./img/stackCard-six-icon.svg"
