export { default as whiteArrow } from "./white-arrow.png"

export { default as blueArrow } from "./blue-arrrow.svg"
export { default as groupIcon } from "./groupIcon.png"
export { default as paymentSummary } from "./heroImg.webp"

export { default as paymentLink } from "./payment-link.svg"
export { default as paymentPage } from "./payment-page.svg"
export { default as qrCodes } from "./qrCode.svg"
export { default as paymentButton } from "./pazment-button.svg"
export { default as autoCollect } from "./auto-collect.svg"
export { default as instant } from "./instant-settlement.svg"
export { default as paymentGatewayImg } from "./payment-gateway-img.svg"
export { default as reminder } from "./remineder-engien.svg"

export { default as stepCardImgOne } from "./stepCardImgOne.webp"
export { default as stepCardImgTwo } from "./stepCardImgTwo.webp"
export { default as stepCardImgThree } from "./stepCardImgThree.webp"
export { default as zeroLeakage } from "./zero-leakage.webp"
export { default as analytics } from "./analytics.webp"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"
export { default as stackCardsixImg } from "./wide-acceptance-network.webp"
export { default as stackCardThreeImg } from "./stack-card-three-img.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as stackCardsixIicon } from "./streamlined-reimbursement-icon.svg"
export { default as stackCardThreeIcon } from "./stackCardThreeIcon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"

export { default as pettyIconOne } from "./pettyIconOne.svg"
export { default as pettyIconTwo } from "./pettyIconTwo.svg"
export { default as pettyIconThree } from "./pettyIconThree.svg"
export { default as pettyIconFour } from "./pettyIconFour.svg"
export { default as pettyIconFive } from "./pettyIconFive.svg"
export { default as pettyIconSix } from "./pettyIconSix.svg"
export { default as pettyIconSeven } from "./pettyIconSeven.svg"
export { default as pettyIconEight } from "./pettyIconEight.svg"
