
server {
    listen 80;
    listen [::]:80;
    server_name enkash.com;
    return 301 https://www.enkash.com$request_uri;
}

server {
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types
      text/plain text/css text/xml
      text/javascript application/x-javascript
      application/xml application/javascript
      application/json
      font/eot
      font/otf
      font/ttf
      image/svg+xml;
    gzip_disable "MSIE [1-6]\.";
    listen 80;
    listen [::]:80;
    server_name www.enkash.com;
    absolute_redirect off;
    client_max_body_size 20M;

     location /resource-video {
        rewrite ^/resource-video(.*)$ /resources/videos/$1 redirect;
    }

    location / {
       proxy_pass http://127.0.0.1:3000;
        add_header Strict-Transport-Security "includeSubdomains";
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header referrer-policy same-origin;
        add_header Feature-Policy "geolocation 'none';gyroscope 'none';fullscreen 'self';";
        add_header Content-Security-Policy "frame-ancestors 'self';";
    }

    # added on 23-10-2024, keep for alteast 1 year
    # Voucher Category Redirect
    location ~ ^/bolt/category/([^/?]+)/?$ {
    rewrite ^/bolt/category/([a-zA-Z0-9\-_]+)/?$ /vouchers/category/$1/ permanent;
    }

}






