export { default as groupIcon } from "./groupIcon.svg"
export { default as paymentSummary } from "./heroImg.webp"
export { default as mealCardImage } from "./collect-payment.webp"

export { default as paymentLinkImage } from "./payment-link.webp"
export { default as shareImage } from "./shareImg.webp"
export { default as paymentOptionImage } from "./payment-option.webp"
export { default as notificationImage } from "./notification.webp"
export { default as secureImage } from "./secure-transition.webp"
export { default as optimizedIcon } from "./website-requierd.webp"
export { default as advancedImage } from "./advanced.webp"

export { default as scrollIconOne } from "./scrollIconOne.svg"
export { default as scrollIconTwo } from "./scrollIconTwo.svg"
export { default as scrollIconThree } from "./scrollIconThree.svg"
export { default as scrollIconFour} from "./make-payments-icon.svg"

export { default as taskIconOne } from "./task-icon-one.svg"
export { default as taskIconTwo } from "./task-icon-two.svg"
export { default as taskIconThree } from "./task-icon-three.svg"
export { default as taskIconFour } from "./task-icon-four.svg"
export { default as taskIconFive } from "./task-icon-five.svg"
export { default as taskIconSix } from "./task-icon-six.svg"
export { default as taskIconSeven } from "./task-icon-seven.svg"
