export { default as heroCardImg } from "./hero card.webp"

export { default as tabIconOne } from "./tab-icon-one.svg"
export { default as tabIcontwo } from "./tab-icon-two.svg"
export { default as tabIconThree } from "./tab-icon-three.svg"
export { default as tabIconFour } from "./tab-icon-four.svg"
export { default as tabIconFive } from "./tab-icon-five.svg"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"
export { default as enforceApproval } from "./enforce-approval.webp"
export { default as secureCompliant } from "./secure-compliant.webp"

export { default as fuelCardImg } from "./fuel-card.svg"
export { default as mealCardImg } from "./meal-card.webp"
export { default as purchesCardImg } from "./purches-card.svg"
export { default as sassCardImg } from "./sass-card.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.webp"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as PettyCashDigitizationImage } from "./petty-cash-digitization.webp"
export { default as vendorPaymentImage } from "./vendor-payment.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
export { default as EnforceIcon } from "./enforce-icon.svg"
export { default as SecureCompliantIcon } from "./secure-compliant-icon.svg"
export { default as success } from "./success.svg"
export { default as statsBg } from "./statsBg.webp"
export { default as GridBgImage } from "./grid-bg-image.webp"

export { default as itemIcon1 } from "./itemIcon1.svg"
export { default as itemIcon2 } from "./itemIcon2.svg"
export { default as itemIcon3 } from "./itemIcon3.svg"
export { default as itemIcon4 } from "./itemIcon4.svg"
export { default as itemIcon5 } from "./itemIcon5.svg"
export { default as itemIcon6 } from "./itemIcon6.svg"



