export { default as officeImg } from "./office-img.png"
export { default as greenArrow } from "./green-arrow.svg"
export { default as gradientBg } from "./gradient-bg.png"
export { default as cardBg } from "./card-bg.png"
export { default as faqBg } from "./faq-bg.svg"
export { default as heavyLiftingIconOne } from "./heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./heavy-lifting-icon-four.svg"
export { default as creditCard } from "./credit_card.svg"
export { default as approved } from "./approved.svg"
export { default as policyIcon } from "./policyIcon.svg"

// new images
export { default as clockIcon } from "./clockIcon.svg"
export { default as multiCardIcon } from "./multi-card.svg"
export { default as realTimeTrakingIcon } from "./real-time-traking.svg"
export { default as securityIcon } from "./security-icon.svg"
export { default as instantActionImg } from "./instant-action-img.svg"
export { default as spendAnalylicsImg } from "./spend-analylics.svg"
export { default as motherCardImg } from "./meal-card-bg.webp"
export { default as rbiLogo } from "./rbi.svg"
export { default as corporateCard } from "./corporate-card.svg"
export { default as corporateCardIcon } from "./oneClick.svg"
export { default as mealCardImg } from "./meal-card.png"
export { default as fuelCardImg } from "./fuel-card.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.png"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as purchesCardImg } from "./purches-card.svg"
export { default as digitalCardImg } from "./digital-marketing-card.svg"
export { default as sassCardImg } from "./sass-card.svg"
export { default as fleetCardImg } from "./fleet-card.svg"
// .../////
export { default as paymentGatwayImg } from "./payment-gateway.png"
export { default as paymentGatwayIcon } from "./payment-gateway-icon.svg"
export { default as paymentLinkImg } from "./payment-link.png"
export { default as paymentLinkIcon } from "./payment-links-icon.svg"
export { default as paymentButtonImg } from "./payment-button.png"
export { default as paymentButtonIcon } from "./payment-button-icon.svg"
export { default as paymentPageImg } from "./payment-page.png"
export { default as paymentPageIcon } from "./payment-page-icon.svg"
export { default as upiImg } from "./upi.png"
export { default as upiIcon } from "./upi-payment-icon.svg"
export { default as qrCodeImg } from "./qr-code.png"
export { default as qrCodeIcon } from "./qr-code-icon.svg"
export { default as circles } from "./Circle 5.svg"
export { default as instantSettelmentIcon } from "./instant-settlement.-iconsvg.svg"
export { default as instantSettelmentImg } from "./instant-settlement.-Img.webp"
export { default as affordabilityIcon } from "./afordability-suits-icon.svg"
export { default as affordabilityImg } from "./afordability-suits-img.webp"
export { default as mealCardImage } from "./meal-card.webp"
export { default as cardRotatingImage } from "./card-roatating.svg"
export { default as podiumImage } from "./podium.png"
export { default as heroCardImg } from "./hero card.webp"
export { default as tabIconOne } from "./tab-icon-one.svg"
export { default as tabIcontwo } from "./tab-icon-two.svg"
export { default as tabIconThree } from "./tab-icon-three.svg"
export { default as tabIconFour } from "./tab-icon-four.svg"
export { default as tabIconFive } from "./tab-icon-five.svg"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
