export { default as bg1 } from "./img/MealCard.webp"
export { default as bg2 } from "./img/Fuel-card.webp"
export { default as bg3 } from "./img/digital-marketing.jpg"
export { default as bg4 } from "./img/logistic-card.webp"
export { default as bg5 } from "./img/payroll-card.webp"

export { default as notificationImage } from "./img/notification.webp"
export { default as paymentLinkImage } from "./img/payment-link.webp"
export { default as paymentOptionImage } from "./img/payment-option.webp"
export { default as secureImage } from "./img/secure-transition.webp"
export { default as shareImage } from "./img/shareImg.webp"

export { default as tabIconOne } from "./img/tab-icon-one.svg"
export { default as tabIconTwo } from "./img/tab-icon-two.svg"
export { default as tabIconThree } from "./img/tab-icon-three.svg"
export { default as tabIconFour } from "./img/tab-icon-four.svg"
export { default as tabIconFive } from "./img/tab-icon-five.svg"

export { default as taskIconOne } from "./img/task-icon-one.svg"
export { default as taskIconTwo } from "./img/task-icon-two.svg"
export { default as taskIconThree } from "./img/task-icon-three.svg"
export { default as taskIconFour } from "./img/task-icon-four.svg"
export { default as paymentSummary } from "./img/heroImg.webp"
