export { default as groupIcon } from "./groupIcon.svg"
export { default as paymentSummary } from "./heroImg.webp"
export { default as mealCardImage } from "./collect-payment.webp"

export { default as realTimeIcon } from "./real-time.svg"
export { default as hundredPercentIcon } from "./100.svg"
export { default as activationIcon } from "./activation.svg"

export { default as autoCollect } from "./auto-collect.svg"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as notificationImage } from "./notification.webp"
export { default as paymentButton } from "./pazment-button.svg"
export { default as paymentGatewayImg } from "./payment-gateway-img.svg"
export { default as paymentLink } from "./payment-link.svg"
export { default as paymentLinkImage } from "./payment-link.webp"
export { default as paymentOptionImage } from "./payment-option.webp"
export { default as qrCodes } from "./qrCode.svg"
export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as reminder } from "./remineder-engien.svg"
export { default as scrollIconOne } from "./scrollIconOne.svg"
export { default as scrollIconTwo } from "./scrollIconTwo.svg"
export { default as scrollIconThree } from "./scrollIconThree.svg"
export { default as secureImage } from "./secure-transition.webp"
export { default as shareImage } from "./shareImg.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"

export { default as taskIconOne } from "./task-icon-one.svg"
export { default as taskIconTwo } from "./task-icon-two.svg"
export { default as taskIconThree } from "./task-icon-three.svg"
export { default as taskIconFour } from "./task-icon-four.svg"
export { default as taskIconFive } from "./task-icon-five.svg"

export { default as upiImg } from "./upi-payments.webp"
