export { default as officeImg } from "./office-img.png"
export { default as whiteArrow } from "./white-arrow.png"
export { default as greenArrow } from "./green-arrow.svg"
export { default as gradientBg } from "./gradient-bg.png"
export { default as cardBg } from "./card-bg.png"
export { default as acceleratedGrowthImg } from "./acceleratedGrowthImg.svg"
export { default as heavyLiftingIconOne } from "./heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./heavy-lifting-icon-four.svg"
export { default as creditCard } from "./credit_card.svg"
export { default as blueArrow } from "./blue-arrrow.svg"
export { default as approved } from "./approved.svg"
export { default as policyIcon } from "./policyIcon.svg"
export { default as groupIcon } from "./groupIcon.svg"
export { default as paymentSummary } from "./heroImg.webp"
export { default as integration } from "./integration.svg"
export { default as paymenyMethod } from "./payment-method.svg"
export { default as rank } from "./rank.svg"
export { default as leftHand } from "./LEFT HAND.svg"
export { default as support } from "./support.svg"
export { default as dashboard } from "./dashboard.svg"
export { default as paymentLink } from "./payment-link.svg"
export { default as paymentPage } from "./payment-page.svg"
export { default as qrCodes } from "./qrCode.svg"
export { default as invoices } from "./invoices.svg"
export { default as paymentButton } from "./pazment-button.svg"
export { default as autoCollect } from "./auto-collect.svg"
export { default as instant } from "./instant-settlement.svg"
export { default as reminder } from "./remineder-engien.svg"
export { default as paymentGateway } from "./payment-gateway.svg"
// .........

export { default as mealCardImage } from "./collect-payment.webp"
export { default as paymentLinkImage } from "./payment-link.webp"
export { default as shareImage } from "./shareImg.webp"
export { default as paymentOptionImage } from "./payment-option.webp"
export { default as notificationImage } from "./notification.webp"
export { default as secureImage } from "./secure-transition.webp"
export { default as optimizedIcon } from "./website-requierd.webp"
export { default as hundredPercentIcon } from "./100%.svg"
export { default as activationIcon } from "./activation.svg"
export { default as realTimeIcon } from "./real-time.svg"
export { default as greenIcon } from "./green-icon.svg"

export { default as scrollIconOne } from "./scrollIconOne.svg"
export { default as scrollIconTwo } from "./scrollIconTwo.svg"
export { default as scrollIconThree } from "./scrollIconThree.svg"

export { default as taskIconOne } from "./task-icon-one.svg"
export { default as taskIconTwo } from "./task-icon-two.svg"
export { default as taskIconThree } from "./task-icon-three.svg"
export { default as taskIconFour } from "./task-icon-four.svg"
export { default as taskIconFive } from "./task-icon-five.svg"
export { default as taskIconSix } from "./task-icon-six.svg"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as TravelImage } from "./TravelImage.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as TravelIcon } from "./TravelIcon.svg"
