export { default as userPlus } from "./img/user-plus.png";
export { default as userTick } from "./img/user-tick.png";
export { default as numberOne } from "./img/number-one.png";
export { default as numberTwo } from "./img/number-two.png";
export { default as numberThree } from "./img/number-three.png";
export { default as stack } from "./img/stack.png";
export { default as automateIcon } from "./img/automate-icon.png";
export { default as blueBoxIcon } from "./img/blue-box-icon.png";
export { default as twoBoxIcon } from "./img/two-box-icon.png";
export { default as circleRupeeIcon } from "./img/circle-rupee-icon.png";
export { default as teamImg } from "./img/team-img.png";
export { default as inc42 } from "./img/inc42.png";
export { default as paymentAndCardSummit } from "./img/payment-and-card-summit.png";
export { default as nasscom } from "./img/nasscom.png";
export { default as testimonials } from "./img/testimonials.png";
export { default as userImg } from "./img/user-img.png";
export { default as axisBankLogo } from "./img/axis-bank-logo.png";
export { default as iciciBankLogo } from "./img/icici-bank-logo.png";
export { default as rupayLogo } from "./img/rupay-logo.png";
export { default as sbmLogo } from "./img/sbm-logo.png";
export { default as visaLogo } from "./img/visa-logo.png";
export { default as playButton } from "./img/watch.png";
export { default as rainbowOne } from "./img/stack-one.png";
export { default as rainbowOneMobile } from "./img/stack-one-mobile.png";
export { default as rainbowTwo } from "./img/stack-two.png";
export { default as rainbowTwoMobile } from "./img/stack-two-mobile.png";
export { default as rainbowThree } from "./img/stack-three.png";
export { default as rainbowThreeMobile } from "./img/stack-three-mobile.png";
export { default as polygonOne } from "./img/polygon-one.png";
export { default as polygonTwo } from "./img/polygon-two.png";
export { default as polygonThree } from "./img/polygon-three.png";
export { default as blueBlackLine } from "./img/blue-black-line.png";
export { default as threeDownArrow } from "./img/three-down-arrow.png";
export { default as mobileTestimonial } from "./img/mobile-testimonial-image.png";
export { default as polygonOneShadow } from "./img/polygon-one-shadow.png";
export { default as leftBlueGradient } from "./img/left-blue-gradient.png";
export { default as leftCardGradient } from "./img/left-card-gradient.png";
export { default as rightCardGradient } from "./img/right-card-gradient.png";
export { default as kotakLogo } from "./img/kotak-bank-logo.png";
export { default as hdfcLogo } from "./img/hdfc-logo.png";
export { default as masterCardLogo } from "./img/master-card-logo.png";
export { default as greenBg } from "./img/green-gradient-bg.png";
export { default as box8Logo } from "./img/box-eight-logo.png";
export { default as firstCryLogo } from "./img/first-cry-logo.png";
export { default as landmarkLogo } from "./img/landmark-group.webp";
export { default as everestLogo } from "./img/everest-logo.png";
export { default as pristynCareLogo } from "./img/pristyn-care-logo.png";
export { default as cureFoodsLogo } from "./img/curefoods-logo.png";
export { default as infraMarketLogo } from "./img/infra-market-logo.png";
export { default as integration } from "./img/Integration.png";

export const manageAnimation = () => import("./img/lottie/manage.json");
export const automateAnimation = () => import("./img/lottie/automate.json");
export const trackAnimation = () => import("./img/lottie/track.json");
export const optimizeAnimation = () => import("./img/lottie/optimize.json");
