// previous set
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as fleetCardImg } from "./fleet-card.svg"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as fuelCardImg } from "./fuel-card.svg"
export { default as purchesCardImg } from "./purches-card.svg"
export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as sassCardImg } from "./sass-card.svg"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.png"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as circles } from "./Circle 5.svg"
export { default as mealCardImage } from "./meal-card.webp"
export { default as cardRotatingImage } from "./card-roatating.svg"
export { default as heroCardImg } from "./hero card.webp"
export { default as payrollCardImg } from "./payroll-card.webp"

// newly added set
export { default as iconOne } from "./auto-collect.svg"
export { default as iconTwo } from "./subsccribtion.svg"
export { default as iconThree } from "./enach.svg"
export { default as iconFour } from "./benifits-icon.svg"
export { default as autoCollect } from "./autoCollectImg.webp"
export { default as subscribtion } from "./subscribtionImg.webp"
export { default as eNach } from "./eNachImg.webp"
export { default as firstIcon } from "./icon-one.svg"
export { default as secondIcon } from "./icon-two.svg"
export { default as thirdIcon } from "./icon-three.svg"
export { default as fourthIcon } from "./icon-four.svg"
export { default as benfits } from "./fourthIMG.webp"
