// previous set
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as fleetCardImg } from "./fleet-card.svg"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as fuelCardImg } from "./fuel-card.svg"
export { default as purchesCardImg } from "./purches-card.svg"
export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as sassCardImg } from "./sass-card.svg"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.png"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as circles } from "./Circle 5.svg"
export { default as mealCardImage } from "./meal-card.webp"
export { default as cardRotatingImage } from "./card-roatating.svg"
export { default as heroCardImg } from "./hero card.webp"
export { default as payrollCardImg } from "./payroll-card.webp"

// newly added set
export { default as iconOne } from "./auto-collect.svg"
export { default as iconTwo } from "./subsccribtion.svg"
export { default as iconThree } from "./enach.svg"
export { default as iconFour } from "./benifits-icon.svg"
export { default as autoCollect } from "./autoCollectImg.webp"
export { default as subscribtion } from "./subscribtionImg.webp"
export { default as eNach } from "./eNachImg.webp"
export { default as firstIcon } from "./icon-one.svg"
export { default as secondIcon } from "./icon-two.svg"
export { default as thirdIcon } from "./icon-three.svg"
export { default as fourthIcon } from "./icon-four.svg"
export { default as success } from "./success.svg"
export { default as benfits } from "./fourthIMG.webp"
export { default as heroImage } from "./hero-image.webp"
export { default as statsBg } from "./stats-bg.webp"

export { default as caraouselIcon11 } from "./caraouselIcon11.svg"
export { default as caraouselIcon12 } from "./caraouselIcon12.svg"
export { default as caraouselIcon13 } from "./caraouselIcon13.svg"
export { default as caraouselIcon14 } from "./caraouselIcon14.svg"
export { default as bulletPointSectionImg } from "./bullet-point-section-img.webp"
export { default as dataIcon1 } from "./dataIcon1.svg"
export { default as dataIcon2 } from "./dataIcon2.svg"
export { default as dataIcon3 } from "./dataIcon3.svg"
export { default as dataIcon4 } from "./dataIcon4.svg"
export { default as dataIcon5 } from "./dataIcon5.svg"
export { default as dataImage1 } from "./dataImage1.webp"
export { default as dataImage2 } from "./dataImage2.webp"
export { default as dataImage3 } from "./dataImage3.webp"
export { default as dataImage4 } from "./dataImage4.webp"
export { default as dataImage5 } from "./dataImage5.webp"
export { default as compititorIcon } from "./compititor-icon.svg"
export { default as succesicon } from "./succesicon.svg"
export { default as EmployeeBenefits } from "./employer-benefits.webp"
export { default as EmployeeBenefit1 } from "./employee-benefits2.webp"
export { default as categoryIcon1 } from "./categoryIcon1.svg"
export { default as categoryIcon2 } from "./categoryIcon2.svg"
export { default as categoryIcon3 } from "./categoryIcon3.svg"
export { default as categoryIcon4 } from "./categoryIcon4.svg"
export { default as categoryIcon5 } from "./categoryIcon5.svg"
export { default as categoryIcon6 } from "./categoryIcon6.svg"
export { default as categoryIcon7 } from "./categoryIcon7.svg"
export { default as categoryIcon8 } from "./categoryIcon8.svg"                                 