
export { default as groupIcon } from "./groupIcon.png"
export { default as paymentSummary } from "./heroImg.webp"
export { default as acceleratedGrowthImg } from "./acceleratedGrowthImg.svg"
export { default as heavyLiftingIconOne } from "./heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./heavy-lifting-icon-four.svg"
export { default as creditCard } from "./credit_card.svg"


export { default as paymentButton } from "./pazment-button.svg"
export { default as mealCardImg } from "./meal-card.png"
export { default as fuelCardImg } from "./fuel-card.svg"

export { default as instant } from "./instant-settlement.svg"
export { default as reminder } from "./remineder-engien.svg"
export { default as paymentGateway } from "./payment-gateway.svg"
// .........

export { default as mealCardImage } from "./collect-payment.webp"
export { default as paymentLinkImage } from "./payment-link.webp"
export { default as shareImage } from "./shareImg.webp"
export { default as paymentOptionImage } from "./payment-option.webp"
export { default as notificationImage } from "./notification.webp"
export { default as secureImage } from "./secure-transition.webp"
export { default as optimizedIcon } from "./website-requierd.webp"
export { default as hundredPercentIcon } from "./100%.svg"
export { default as activationIcon } from "./activation.svg"
export { default as realTimeIcon } from "./real-time.svg"
export { default as customizableIcon } from "./customizableIcon.svg"

export { default as scrollIconOne } from "./scrollIconOne.svg"
export { default as scrollIconTwo } from "./scrollIconTwo.svg"
export { default as scrollIconThree } from "./scrollIconThree.svg"
export { default as scrollIconFour } from "./scrollIconFoursvg.svg"

export { default as taskIconOne } from "./task-icon-one.svg"
export { default as taskIconTwo } from "./task-icon-two.svg"
export { default as taskIconThree } from "./task-icon-three.svg"
export { default as taskIconFour } from "./task-icon-four.svg"
export { default as taskIconFive } from "./task-icon-five.svg"
export { default as taskIconSix } from "./task-icon-six.svg"
export { default as faqBg } from "./secondFaq.webp"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"
export { default as stackCardSixImg } from "./stackCard-six-image.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
export { default as stackCardSixIcon } from "./stackCard-six-icon.svg"

export { default as giftCard } from "./gift-card.webp"
export { default as offers } from "./offers.webp"
export { default as incentive } from "./incentive.webp"
export { default as vouchers } from "./vouchers.webp"
