// AUTO-GENERATED FILE — DO NOT EDIT
// Source file: Glossary Testing (1) (1).xlsx
// Total terms: 33

export type GlossaryTerm = {
    keyword: string
    slug: string
    metaTitle?: string
    metaDescription?: string
    definition: string
    businessContext?: string
    howItWorks?: string
    sectionHeading1?: string
    sectionDescription1?: string
    sectionHeading2?: string
    sectionDescription2?: string
    sectionHeading3?: string
    sectionDescription3?: string
    sectionHeading4?: string
    sectionDescription4?: string
    relatedBlogs?: string
    sheet: string
  }
  
  export const GLOSSARY_DATA: GlossaryTerm[] = [
    {
      keyword: 'Asset',
      slug: 'asset',
      metaTitle: 'Asset Meaning in Accounting | Types of Assets with Examples',
      metaDescription: 'Learn the meaning of asset in accounting, business, and finance. Understand types of assets—current, fixed, financial, digital, and intangible',
      definition: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      businessContext: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading1: 'Meaning',
      sectionDescription1: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading3: 'Types of Assets',
      sectionDescription3: '1. Current Assets\n\nShort-term assets expected to be converted into cash within a year.\nExamples: cash, inventory, receivables, prepaid expenses.\n\n2. Non-current or Fixed Assets\n\nLong-term assets used for operations.\nExamples: machinery, buildings, furniture, vehicles.\n\n3. Financial Assets\n\nInvestments or instruments representing monetary value.\nExamples: deposits, mutual funds, securities.\n\n4. Digital Assets\n\nIntangible assets used for technology and operations.\nExamples: software licenses, digital tools, cloud subscriptions, proprietary data.\n\n5. Intangible Assets\n\nNon-physical assets that provide long-term value.\nExamples: trademarks, patents, goodwill, brand rights.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'A'
    },
    {
      keyword: 'Asset Management',
      slug: 'asset-management',
      metaTitle: 'Asset Management Meaning | What Is Asset Management in Business',
      metaDescription: 'Asset management helps businesses track, maintain, and optimize assets across their lifecycle. Learn its meaning, process, and real-world examples.',
      definition: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      businessContext: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionHeading1: 'What Is Asset Management',
      sectionDescription1: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionHeading3: 'Examples',
      sectionDescription3: 'i. A company tracking and maintaining its laptop inventory for all employees.\n\nii. A manufacturing unit scheduling preventive maintenance for machinery.\n\niii. A finance team recording depreciation for all capital equipment during audits.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'A'
    },
    {
      keyword: 'Asset Transfer',
      slug: 'asset-transfer',
      metaTitle: 'Asset Transfer Meaning | What Is Asset Transfer in Business',
      metaDescription: 'Learn what asset transfer means in business and accounting. Understand asset transfer process, compliance, and examples under Indian laws and regulations.',
      definition: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      businessContext: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading1: 'What is Asset Transfer',
      sectionDescription1: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading3: 'How Asset Transfers Work',
      sectionDescription3: 'The asset transfer process typically involves:\n\ni. Identification of the asset and its current ownership details\n\nii. Valuation based on book value, fair value, or market price\n\niii. Approval through internal finance controls or board resolutions if required\n\niv. Documentation such as transfer notes, agreements, or handover reports\n\nv. Updating records in ERP, accounting systems, and registers\n\nvi. Compliance with tax or regulatory rules if applicable',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'A'
    },
    {
      keyword: 'Accounting',
      slug: 'accounting',
      definition: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      businessContext: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading1: 'What is Accounting',
      sectionDescription1: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading3: 'Key Functions of Accounting',
      sectionDescription3: 'i. Recording - Capturing day-to-day financial activities such as payments, receipts, vendor invoices, reimbursements, and card transactions.\n\nii. Classification - Organising entries into ledgers such as assets, liabilities, expenses, income, or equity for accurate analysis.\n\niii. Summarisation - Preparing financial statements like the Profit and Loss Statement, Balance Sheet, and Cash Flow Statement.\n\niv. Reporting - Presenting financial information to management, auditors, lenders, investors, and regulators.\n\nv. Reconciliation - Ensuring internal books match external records including bank statements, corporate card data, UPI transactions, and vendor accounts.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/bookkeeping-vs-accounting-key-differences-every-business-should-know',
      sheet: 'A'
    },
    {
      keyword: 'Accounting Cycle',
      slug: 'glossary/accounting-cycle',
      definition: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      businessContext: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading1: 'What is Accounting Cycle',
      sectionDescription1: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading3: 'How the Cycle Works',
      sectionDescription3: '1. Capture Transactions - Identifying all financial activities such as vendor invoices, reimbursements, card spends, bank entries, and revenue events.\n\n2. Record Journal Entries - Documenting transactions with correct debits and credits in the appropriate journals.\n\n3. Update Ledger Accounts - Posting journal entries to ledgers like expenses, assets, liabilities, and revenue for organised financial tracking.\n\n4. Prepare Trial Balance - Ensuring debits and credits match to detect discrepancies early.\n\n5. Record Adjustments - Adding accruals, prepayments, depreciation, amortisation, and corrections to reflect the actual financial position.\n\n6. Prepare Adjusted Trial Balance - Validating accuracy after adjustments and ensuring accounts are balanced for reporting.\n\n7. Generate Financial Statements - Creating the Profit and Loss statement, Balance Sheet, and Cash Flow statement for internal and external stakeholders.\n\n8. Close the Books - Resetting temporary accounts to start the next accounting period with clean, accurate records.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/understanding-the-accounting-cycle-importance-steps-and-flowchart',
      sheet: 'A'
    },
    {
      keyword: 'Accrual Accounting',
      slug: 'glossary/accrual-accounting',
      definition: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      businessContext: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading3: 'How it Works',
      sectionDescription3: 'i. Revenue recognition: Recorded when a company delivers goods or services, even if payment is pending.\n\nii. Expense recognition: Recorded when costs occur, such as vendor invoices, utilities, or salaries, regardless of payment timing.\n\niii. Adjustments: Includes accruals, prepayments, depreciation, and amortization to present accurate period-end results.\n\nThis ensures financial statements reflect economic reality rather than cash movement alone.',
      sheet: 'A'
    },
    {
      keyword: 'Accounting Method',
      slug: 'glossary/accounting-method',
      definition: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      businessContext: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading3: 'Types of Accounting Methods',
      sectionDescription3: 'i. Cash Accounting\nRecords income and expenses only when cash is received or paid. It is best for smaller businesses that want a straightforward view of cash movement.\n\nii. Accrual Accounting\nRecords income when earned and expenses when incurred, even if cash moves later. It is used by companies that need accurate reporting, forecasting, and audit readiness.\n\niii. Hybrid Method\nA mix of cash and accrual treatment. It is used in limited cases since Indian tax rules generally prefer consistent use of either cash or accrual.',
      sheet: 'A'
    },
    {
      keyword: 'Alternative Minimum Tax (AMT)',
      slug: 'glossary/alternative-maximum-tax',
      metaTitle: 'Alternative Minimum Tax (AMT) Meaning | AMT in India Explained',
      metaDescription: 'Learn what Alternative Minimum Tax (AMT) is, how it works in India, applicable rates, and who must pay AMT under the Income Tax Act.',
      definition: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      businessContext: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      sectionHeading2: 'In the Indian Context',
      sectionDescription2: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading3: 'How AMT Works',
      sectionDescription3: 'In India, Alternative Minimum Tax is applied to ensure that non-corporate taxpayers who claim certain profit-linked deductions still pay a minimum amount of tax.\n\nTaxpayers must compute tax using both:\n\ni. Normal Income Tax Provisions\n\nii. Alternative Minimum Tax (AMT) using Adjusted Total Income\n\nThe higher of the two becomes the final tax payable.',
      sectionHeading4: 'AMT Rates (India)',
      sectionDescription4: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      relatedBlogs: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      sheet: 'A'
    },
    {
      keyword: 'Audit',
      slug: 'glossary/audit',
      definition: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      businessContext: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading1: 'What is Audit',
      sectionDescription1: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading3: 'Types of Audits',
      sectionDescription3: 'i. Statutory Audit - Mandatory review of financial statements for companies and certain entities as per the Companies Act.\n\nii. Internal Audit - Ongoing assessment of internal controls, processes, and risk systems to ensure operational efficiency.\n\niii. Tax Audit - Required under Section 44AB of the Income Tax Act for businesses above specified turnover thresholds.\n\niv. GST Audit - Review of GST filings, input tax credit, and compliance accuracy (applicable under certain turnover limits or notices).\n\nv. Special / Compliance Audits - Audits ordered by regulators, lenders, or investors to examine specific areas like expenses, systems, or governance.',
      sheet: 'A'
    },
    {
      keyword: 'Audit Risk',
      slug: 'glossary/audit-risk',
      definition: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      businessContext: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading1: 'What is Audit Risk',
      sectionDescription1: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading3: 'Why Audit Risk Matters for Businesses',
      sectionDescription3: 'i. Ensures financial statements reflect true and fair information.\n\nii. Strengthens internal controls and reduces operational leakages.\n\niii. Minimizes chances of penalties, tax notices, or compliance findings.\n\niv. Builds trust with investors, auditors, banks, and stakeholders.\n\nv. Helps finance teams design better documentation and approval processes.',
      sheet: 'A'
    },
    {
      keyword: 'AML (Anti-Money Laundering)',
      slug: 'glossary/anti-money-laundering',
      definition: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      businessContext: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading1: 'Definition',
      sectionDescription1: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      sectionHeading2: 'Regulatory Context',
      sectionDescription2: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading3: 'What AML Includes',
      sectionDescription3: '1. KYC (Know Your Customer)\nVerifying the identity and legitimacy of customers before onboarding.\n\n2. CDD & Enhanced Due Diligence\nAssessing customer risk and applying deeper checks for high-risk customers.\n\n3. Transaction Monitoring\nDetecting unusual spending patterns, large cash movements, or suspicious activities.\n\n4. Screening\nChecking customers against sanction lists, watchlists, negative media, and PEP (Politically Exposed Persons) databases.\n\n5. Reporting\nFiling mandatory reports to FIU-IND such as STRs (Suspicious Transaction Reports) or CTRs (Cash Transaction Reports).\n\n6. Record Keeping\nMaintaining KYC and transaction logs for regulatory audit and examinations.',
      sheet: 'A'
    },
    {
      keyword: 'Asset',
      slug: 'bsset',
      metaTitle: 'Asset Meaning in Accounting | Types of Assets with Examples',
      metaDescription: 'Learn the meaning of asset in accounting, business, and finance. Understand types of assets—current, fixed, financial, digital, and intangible',
      definition: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      businessContext: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading1: 'What Is Asset Management',
      sectionDescription1: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading3: 'Types of Assets',
      sectionDescription3: '1. Current Assets\n\nShort-term assets expected to be converted into cash within a year.\nExamples: cash, inventory, receivables, prepaid expenses.\n\n2. Non-current or Fixed Assets\n\nLong-term assets used for operations.\nExamples: machinery, buildings, furniture, vehicles.\n\n3. Financial Assets\n\nInvestments or instruments representing monetary value.\nExamples: deposits, mutual funds, securities.\n\n4. Digital Assets\n\nIntangible assets used for technology and operations.\nExamples: software licenses, digital tools, cloud subscriptions, proprietary data.\n\n5. Intangible Assets\n\nNon-physical assets that provide long-term value.\nExamples: trademarks, patents, goodwill, brand rights.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'B'
    },
    {
      keyword: 'Asset Management',
      slug: 'asset-management',
      metaTitle: 'Asset Management Meaning | What Is Asset Management in Business',
      metaDescription: 'Asset management helps businesses track, maintain, and optimize assets across their lifecycle. Learn its meaning, process, and real-world examples.',
      definition: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      businessContext: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionDescription1: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionHeading3: 'Examples',
      sectionDescription3: 'i. A company tracking and maintaining its laptop inventory for all employees.\n\nii. A manufacturing unit scheduling preventive maintenance for machinery.\n\niii. A finance team recording depreciation for all capital equipment during audits.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'B'
    },
    {
      keyword: 'Asset Transfer',
      slug: 'asset-transfer',
      metaTitle: 'Asset Transfer Meaning | What Is Asset Transfer in Business',
      metaDescription: 'Learn what asset transfer means in business and accounting. Understand asset transfer process, compliance, and examples under Indian laws and regulations.',
      definition: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      businessContext: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading1: 'What is Asset Transfer',
      sectionDescription1: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading3: 'How Asset Transfers Work',
      sectionDescription3: 'The asset transfer process typically involves:\n\ni. Identification of the asset and its current ownership details\n\nii. Valuation based on book value, fair value, or market price\n\niii. Approval through internal finance controls or board resolutions if required\n\niv. Documentation such as transfer notes, agreements, or handover reports\n\nv. Updating records in ERP, accounting systems, and registers\n\nvi. Compliance with tax or regulatory rules if applicable',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'B'
    },
    {
      keyword: 'Accounting',
      slug: 'accounting',
      definition: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      businessContext: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading1: 'What is Accounting',
      sectionDescription1: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading3: 'Key Functions of Accounting',
      sectionDescription3: 'i. Recording - Capturing day-to-day financial activities such as payments, receipts, vendor invoices, reimbursements, and card transactions.\n\nii. Classification - Organising entries into ledgers such as assets, liabilities, expenses, income, or equity for accurate analysis.\n\niii. Summarisation - Preparing financial statements like the Profit and Loss Statement, Balance Sheet, and Cash Flow Statement.\n\niv. Reporting - Presenting financial information to management, auditors, lenders, investors, and regulators.\n\nv. Reconciliation - Ensuring internal books match external records including bank statements, corporate card data, UPI transactions, and vendor accounts.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/bookkeeping-vs-accounting-key-differences-every-business-should-know',
      sheet: 'B'
    },
    {
      keyword: 'Accounting Cycle',
      slug: 'glossary/accounting-cycle',
      definition: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      businessContext: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading1: 'What is Accounting Cycle',
      sectionDescription1: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading3: 'How the Cycle Works',
      sectionDescription3: '1. Capture Transactions - Identifying all financial activities such as vendor invoices, reimbursements, card spends, bank entries, and revenue events.\n\n2. Record Journal Entries - Documenting transactions with correct debits and credits in the appropriate journals.\n\n3. Update Ledger Accounts - Posting journal entries to ledgers like expenses, assets, liabilities, and revenue for organised financial tracking.\n\n4. Prepare Trial Balance - Ensuring debits and credits match to detect discrepancies early.\n\n5. Record Adjustments - Adding accruals, prepayments, depreciation, amortisation, and corrections to reflect the actual financial position.\n\n6. Prepare Adjusted Trial Balance - Validating accuracy after adjustments and ensuring accounts are balanced for reporting.\n\n7. Generate Financial Statements - Creating the Profit and Loss statement, Balance Sheet, and Cash Flow statement for internal and external stakeholders.\n\n8. Close the Books - Resetting temporary accounts to start the next accounting period with clean, accurate records.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/understanding-the-accounting-cycle-importance-steps-and-flowchart',
      sheet: 'B'
    },
    {
      keyword: 'Accrual Accounting',
      slug: 'glossary/accrual-accounting',
      definition: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      businessContext: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading3: 'How it Works',
      sectionDescription3: 'i. Revenue recognition: Recorded when a company delivers goods or services, even if payment is pending.\n\nii. Expense recognition: Recorded when costs occur, such as vendor invoices, utilities, or salaries, regardless of payment timing.\n\niii. Adjustments: Includes accruals, prepayments, depreciation, and amortization to present accurate period-end results.\n\nThis ensures financial statements reflect economic reality rather than cash movement alone.',
      sheet: 'B'
    },
    {
      keyword: 'Accounting Method',
      slug: 'glossary/accounting-method',
      definition: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      businessContext: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading3: 'Types of Accounting Methods',
      sectionDescription3: 'i. Cash Accounting\nRecords income and expenses only when cash is received or paid. It is best for smaller businesses that want a straightforward view of cash movement.\n\nii. Accrual Accounting\nRecords income when earned and expenses when incurred, even if cash moves later. It is used by companies that need accurate reporting, forecasting, and audit readiness.\n\niii. Hybrid Method\nA mix of cash and accrual treatment. It is used in limited cases since Indian tax rules generally prefer consistent use of either cash or accrual.',
      sheet: 'B'
    },
    {
      keyword: 'Alternative Minimum Tax (AMT)',
      slug: 'glossary/alternative-maximum-tax',
      metaTitle: 'Alternative Minimum Tax (AMT) Meaning | AMT in India Explained',
      metaDescription: 'Learn what Alternative Minimum Tax (AMT) is, how it works in India, applicable rates, and who must pay AMT under the Income Tax Act.',
      definition: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      businessContext: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      sectionHeading2: 'In the Indian Context',
      sectionDescription2: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading3: 'How AMT Works',
      sectionDescription3: 'In India, Alternative Minimum Tax is applied to ensure that non-corporate taxpayers who claim certain profit-linked deductions still pay a minimum amount of tax.\n\nTaxpayers must compute tax using both:\n\ni. Normal Income Tax Provisions\n\nii. Alternative Minimum Tax (AMT) using Adjusted Total Income\n\nThe higher of the two becomes the final tax payable.',
      sectionHeading4: 'AMT Rates (India)',
      sectionDescription4: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      relatedBlogs: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      sheet: 'B'
    },
    {
      keyword: 'Audit',
      slug: 'glossary/audit',
      definition: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      businessContext: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading1: 'What is Audit',
      sectionDescription1: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading3: 'Types of Audits',
      sectionDescription3: 'i. Statutory Audit - Mandatory review of financial statements for companies and certain entities as per the Companies Act.\n\nii. Internal Audit - Ongoing assessment of internal controls, processes, and risk systems to ensure operational efficiency.\n\niii. Tax Audit - Required under Section 44AB of the Income Tax Act for businesses above specified turnover thresholds.\n\niv. GST Audit - Review of GST filings, input tax credit, and compliance accuracy (applicable under certain turnover limits or notices).\n\nv. Special / Compliance Audits - Audits ordered by regulators, lenders, or investors to examine specific areas like expenses, systems, or governance.',
      sheet: 'B'
    },
    {
      keyword: 'Audit Risk',
      slug: 'glossary/audit-risk',
      definition: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      businessContext: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading1: 'What is Audit Risk',
      sectionDescription1: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading3: 'Why Audit Risk Matters for Businesses',
      sectionDescription3: 'i. Ensures financial statements reflect true and fair information.\n\nii. Strengthens internal controls and reduces operational leakages.\n\niii. Minimizes chances of penalties, tax notices, or compliance findings.\n\niv. Builds trust with investors, auditors, banks, and stakeholders.\n\nv. Helps finance teams design better documentation and approval processes.',
      sheet: 'B'
    },
    {
      keyword: 'AML (Anti-Money Laundering)',
      slug: 'glossary/anti-money-laundering',
      definition: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      businessContext: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading1: 'Definition',
      sectionDescription1: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      sectionHeading2: 'Regulatory Context',
      sectionDescription2: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading3: 'What AML Includes',
      sectionDescription3: '1. KYC (Know Your Customer)\nVerifying the identity and legitimacy of customers before onboarding.\n\n2. CDD & Enhanced Due Diligence\nAssessing customer risk and applying deeper checks for high-risk customers.\n\n3. Transaction Monitoring\nDetecting unusual spending patterns, large cash movements, or suspicious activities.\n\n4. Screening\nChecking customers against sanction lists, watchlists, negative media, and PEP (Politically Exposed Persons) databases.\n\n5. Reporting\nFiling mandatory reports to FIU-IND such as STRs (Suspicious Transaction Reports) or CTRs (Cash Transaction Reports).\n\n6. Record Keeping\nMaintaining KYC and transaction logs for regulatory audit and examinations.',
      sheet: 'B'
    },
    {
      keyword: 'Asset',
      slug: 'bsset',
      metaTitle: 'Asset Meaning in Accounting | Types of Assets with Examples',
      metaDescription: 'Learn the meaning of asset in accounting, business, and finance. Understand types of assets—current, fixed, financial, digital, and intangible',
      definition: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      businessContext: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading1: 'What Is Asset Management',
      sectionDescription1: 'An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.\n\nAssets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.\n\nThey help businesses understand their financial strength, operational capacity, and capital allocation.',
      sectionHeading3: 'Types of Assets',
      sectionDescription3: '1. Current Assets\n\nShort-term assets expected to be converted into cash within a year.\nExamples: cash, inventory, receivables, prepaid expenses.\n\n2. Non-current or Fixed Assets\n\nLong-term assets used for operations.\nExamples: machinery, buildings, furniture, vehicles.\n\n3. Financial Assets\n\nInvestments or instruments representing monetary value.\nExamples: deposits, mutual funds, securities.\n\n4. Digital Assets\n\nIntangible assets used for technology and operations.\nExamples: software licenses, digital tools, cloud subscriptions, proprietary data.\n\n5. Intangible Assets\n\nNon-physical assets that provide long-term value.\nExamples: trademarks, patents, goodwill, brand rights.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'C'
    },
    {
      keyword: 'Asset Management',
      slug: 'asset-management',
      metaTitle: 'Asset Management Meaning | What Is Asset Management in Business',
      metaDescription: 'Asset management helps businesses track, maintain, and optimize assets across their lifecycle. Learn its meaning, process, and real-world examples.',
      definition: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      businessContext: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionDescription1: 'Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.\n\nThe goal is to ensure assets are efficiently utilized, compliant, and cost effective.',
      sectionHeading3: 'Examples',
      sectionDescription3: 'i. A company tracking and maintaining its laptop inventory for all employees.\n\nii. A manufacturing unit scheduling preventive maintenance for machinery.\n\niii. A finance team recording depreciation for all capital equipment during audits.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'C'
    },
    {
      keyword: 'Asset Transfer',
      slug: 'asset-transfer',
      metaTitle: 'Asset Transfer Meaning | What Is Asset Transfer in Business',
      metaDescription: 'Learn what asset transfer means in business and accounting. Understand asset transfer process, compliance, and examples under Indian laws and regulations.',
      definition: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      businessContext: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading1: 'What is Asset Transfer',
      sectionDescription1: 'Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.\n\nTransfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.',
      sectionHeading3: 'How Asset Transfers Work',
      sectionDescription3: 'The asset transfer process typically involves:\n\ni. Identification of the asset and its current ownership details\n\nii. Valuation based on book value, fair value, or market price\n\niii. Approval through internal finance controls or board resolutions if required\n\niv. Documentation such as transfer notes, agreements, or handover reports\n\nv. Updating records in ERP, accounting systems, and registers\n\nvi. Compliance with tax or regulatory rules if applicable',
      relatedBlogs: 'https://www.enkash.com/resources/blog/what-are-fixed-assets',
      sheet: 'C'
    },
    {
      keyword: 'Accounting',
      slug: 'accounting',
      definition: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      businessContext: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading1: 'What is Accounting',
      sectionDescription1: 'Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.\n\nIt forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.',
      sectionHeading3: 'Key Functions of Accounting',
      sectionDescription3: 'i. Recording - Capturing day-to-day financial activities such as payments, receipts, vendor invoices, reimbursements, and card transactions.\n\nii. Classification - Organising entries into ledgers such as assets, liabilities, expenses, income, or equity for accurate analysis.\n\niii. Summarisation - Preparing financial statements like the Profit and Loss Statement, Balance Sheet, and Cash Flow Statement.\n\niv. Reporting - Presenting financial information to management, auditors, lenders, investors, and regulators.\n\nv. Reconciliation - Ensuring internal books match external records including bank statements, corporate card data, UPI transactions, and vendor accounts.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/bookkeeping-vs-accounting-key-differences-every-business-should-know',
      sheet: 'C'
    },
    {
      keyword: 'Accounting Cycle',
      slug: 'glossary/accounting-cycle',
      definition: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      businessContext: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading1: 'What is Accounting Cycle',
      sectionDescription1: 'The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.\n\nA disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.',
      sectionHeading3: 'How the Cycle Works',
      sectionDescription3: '1. Capture Transactions - Identifying all financial activities such as vendor invoices, reimbursements, card spends, bank entries, and revenue events.\n\n2. Record Journal Entries - Documenting transactions with correct debits and credits in the appropriate journals.\n\n3. Update Ledger Accounts - Posting journal entries to ledgers like expenses, assets, liabilities, and revenue for organised financial tracking.\n\n4. Prepare Trial Balance - Ensuring debits and credits match to detect discrepancies early.\n\n5. Record Adjustments - Adding accruals, prepayments, depreciation, amortisation, and corrections to reflect the actual financial position.\n\n6. Prepare Adjusted Trial Balance - Validating accuracy after adjustments and ensuring accounts are balanced for reporting.\n\n7. Generate Financial Statements - Creating the Profit and Loss statement, Balance Sheet, and Cash Flow statement for internal and external stakeholders.\n\n8. Close the Books - Resetting temporary accounts to start the next accounting period with clean, accurate records.',
      relatedBlogs: 'https://www.enkash.com/resources/blog/understanding-the-accounting-cycle-importance-steps-and-flowchart',
      sheet: 'C'
    },
    {
      keyword: 'Accrual Accounting',
      slug: 'glossary/accrual-accounting',
      definition: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      businessContext: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.\n\nIt provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.',
      sectionHeading3: 'How it Works',
      sectionDescription3: 'i. Revenue recognition: Recorded when a company delivers goods or services, even if payment is pending.\n\nii. Expense recognition: Recorded when costs occur, such as vendor invoices, utilities, or salaries, regardless of payment timing.\n\niii. Adjustments: Includes accruals, prepayments, depreciation, and amortization to present accurate period-end results.\n\nThis ensures financial statements reflect economic reality rather than cash movement alone.',
      sheet: 'C'
    },
    {
      keyword: 'Accounting Method',
      slug: 'glossary/accounting-method',
      definition: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      businessContext: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.\n\nFor finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.',
      sectionHeading3: 'Types of Accounting Methods',
      sectionDescription3: 'i. Cash Accounting\nRecords income and expenses only when cash is received or paid. It is best for smaller businesses that want a straightforward view of cash movement.\n\nii. Accrual Accounting\nRecords income when earned and expenses when incurred, even if cash moves later. It is used by companies that need accurate reporting, forecasting, and audit readiness.\n\niii. Hybrid Method\nA mix of cash and accrual treatment. It is used in limited cases since Indian tax rules generally prefer consistent use of either cash or accrual.',
      sheet: 'C'
    },
    {
      keyword: 'Alternative Minimum Tax (AMT)',
      slug: 'glossary/alternative-maximum-tax',
      metaTitle: 'Alternative Minimum Tax (AMT) Meaning | AMT in India Explained',
      metaDescription: 'Learn what Alternative Minimum Tax (AMT) is, how it works in India, applicable rates, and who must pay AMT under the Income Tax Act.',
      definition: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      businessContext: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading1: 'Overview',
      sectionDescription1: 'Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.',
      sectionHeading2: 'In the Indian Context',
      sectionDescription2: 'AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.\n\nIt ensures tax parity and restricts aggressive tax planning through incentives.',
      sectionHeading3: 'How AMT Works',
      sectionDescription3: 'In India, Alternative Minimum Tax is applied to ensure that non-corporate taxpayers who claim certain profit-linked deductions still pay a minimum amount of tax.\n\nTaxpayers must compute tax using both:\n\ni. Normal Income Tax Provisions\n\nii. Alternative Minimum Tax (AMT) using Adjusted Total Income\n\nThe higher of the two becomes the final tax payable.',
      sectionHeading4: 'AMT Rates (India)',
      sectionDescription4: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      relatedBlogs: 'i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.',
      sheet: 'C'
    },
    {
      keyword: 'Audit',
      slug: 'glossary/audit',
      definition: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      businessContext: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading1: 'What is Audit',
      sectionDescription1: 'An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.\n\nThey strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.',
      sectionHeading3: 'Types of Audits',
      sectionDescription3: 'i. Statutory Audit - Mandatory review of financial statements for companies and certain entities as per the Companies Act.\n\nii. Internal Audit - Ongoing assessment of internal controls, processes, and risk systems to ensure operational efficiency.\n\niii. Tax Audit - Required under Section 44AB of the Income Tax Act for businesses above specified turnover thresholds.\n\niv. GST Audit - Review of GST filings, input tax credit, and compliance accuracy (applicable under certain turnover limits or notices).\n\nv. Special / Compliance Audits - Audits ordered by regulators, lenders, or investors to examine specific areas like expenses, systems, or governance.',
      sheet: 'C'
    },
    {
      keyword: 'Audit Risk',
      slug: 'glossary/audit-risk',
      definition: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      businessContext: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading1: 'What is Audit Risk',
      sectionDescription1: 'Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.',
      sectionHeading2: 'Business Context',
      sectionDescription2: 'Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.\n\nIt influences audit planning, internal controls, and the accuracy of financial reporting.\n\nA high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.',
      sectionHeading3: 'Why Audit Risk Matters for Businesses',
      sectionDescription3: 'i. Ensures financial statements reflect true and fair information.\n\nii. Strengthens internal controls and reduces operational leakages.\n\niii. Minimizes chances of penalties, tax notices, or compliance findings.\n\niv. Builds trust with investors, auditors, banks, and stakeholders.\n\nv. Helps finance teams design better documentation and approval processes.',
      sheet: 'C'
    },
    {
      keyword: 'AML (Anti-Money Laundering)',
      slug: 'glossary/anti-money-laundering',
      definition: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      businessContext: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading1: 'Definition',
      sectionDescription1: 'AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.',
      sectionHeading2: 'Regulatory Context',
      sectionDescription2: 'AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:\n\ni. RBI (Reserve Bank of India)\n\nii. FIU-IND (Financial Intelligence Unit – India)\n\niii. Prevention of Money Laundering Act (PMLA)\n\niv. SEBI, IRDAI, and sector regulators\n\nStrong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.',
      sectionHeading3: 'What AML Includes',
      sectionDescription3: '1. KYC (Know Your Customer)\nVerifying the identity and legitimacy of customers before onboarding.\n\n2. CDD & Enhanced Due Diligence\nAssessing customer risk and applying deeper checks for high-risk customers.\n\n3. Transaction Monitoring\nDetecting unusual spending patterns, large cash movements, or suspicious activities.\n\n4. Screening\nChecking customers against sanction lists, watchlists, negative media, and PEP (Politically Exposed Persons) databases.\n\n5. Reporting\nFiling mandatory reports to FIU-IND such as STRs (Suspicious Transaction Reports) or CTRs (Cash Transaction Reports).\n\n6. Record Keeping\nMaintaining KYC and transaction logs for regulatory audit and examinations.',
      sheet: 'C'
    }
  ]