// AUTO-GENERATED FILE — DO NOT EDIT

export type GlossaryTerm = {
  keyword: string
  slug: string
  metaTitle?: string
  metaDescription?: string
  definition: string
  sectionHeading1?: string
  sectionDescription1?: string
  sectionHeading2?: string
  sectionDescription2?: string
  sectionHeading3?: string
  sectionDescription3?: string
  sectionHeading4?: string
  sectionDescription4?: string
  sectionHeading5?: string
  sectionDescription5?: string
  relatedBlogs?: (number | string)[]
  sheet: string
}

export const GLOSSARY_DATA: GlossaryTerm[] = [
  {
    keyword: `Asset`,
    slug: `asset`,
    sheet: `A`,
    definition: `<p>An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.</p>`,
    sectionHeading1: `Meaning`,
    sectionDescription1: `<p>An asset is any resource owned or controlled by a business that has measurable value and can provide future economic benefits. Assets can be physical, financial, digital, or intangible depending on the nature of the business.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>In India, assets are recorded and reported as per the Companies Act, Ind AS, and Income Tax rules.</p><p>Assets play a central role in investment decisions, depreciation calculations, valuation, audits, and financial reporting.</p><p>They help businesses understand their financial strength, operational capacity, and capital allocation.</p>`,
    sectionHeading3: `Types of Assets`,
    sectionDescription3: `<p>1. Current Assets</p><p>Short-term assets expected to be converted into cash within a year.<br>Examples: cash, inventory, receivables, prepaid expenses.</p><p>2. Non-current or Fixed Assets</p><p>Long-term assets used for operations.<br>Examples: machinery, buildings, furniture, vehicles.</p><p>3. Financial Assets</p><p>Investments or instruments representing monetary value.<br>Examples: deposits, mutual funds, securities.</p><p>4. Digital Assets</p><p>Intangible assets used for technology and operations.<br>Examples: software licenses, digital tools, cloud subscriptions, proprietary data.</p><p>5. Intangible Assets</p><p>Non-physical assets that provide long-term value.<br>Examples: trademarks, patents, goodwill, brand rights.</p>`,
    relatedBlogs: [12642, 13675, 12195],
  },
  {
    keyword: `Asset Management`,
    slug: `asset-management`,
    sheet: `A`,
    definition: `<p>Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.</p>`,
    sectionHeading1: `What Is Asset Management`,
    sectionDescription1: `<p>Asset management refers to the process of tracking, maintaining, optimizing, and recording an organization’s tangible and intangible assets throughout their lifecycle, from acquisition to disposal.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Asset management helps businesses understand what assets they own, where they are used, how they are performing, and what value they generate. This includes physical assets like machinery, laptops, vehicles, office equipment, and digital assets such as software licenses, financial investments, and intellectual property.</p><p>The goal is to ensure assets are efficiently utilized, compliant, and cost effective.</p>`,
    sectionHeading3: `Examples`,
    sectionDescription3: `<p>i. A company tracking and maintaining its laptop inventory for all employees.</p><p>ii. A manufacturing unit scheduling preventive maintenance for machinery.</p><p>iii. A finance team recording depreciation for all capital equipment during audits.</p>`,
    relatedBlogs: ["https://www.enkash.com/resources/blog/what-are-fixed-assets", "https://www.enkash.com/resources/blog/what-are-assets-and-liabilities-a-complete-guide", "https://www.enkash.com/resources/blog/fixed-asset-definition-characteristics-and-examples"],
  },
  {
    keyword: `Asset Transfer`,
    slug: `asset-transfer`,
    sheet: `A`,
    definition: `<p>Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.</p>`,
    sectionHeading1: `What is Asset Transfer`,
    sectionDescription1: `<p>Asset transfer refers to the process of moving ownership, control, or rights of an asset from one party to another. This may involve physical assets, digital assets, financial assets, or intangible property.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>In India, asset transfers occur during business restructuring, mergers, acquisitions, internal reallocation, depreciation planning, and disposal of unused assets.</p><p>Transfers must comply with regulations under the Companies Act, Income Tax Act, GST, and Ind AS, depending on the type of asset and the nature of the transfer.</p>`,
    sectionHeading3: `How Asset Transfers Work`,
    sectionDescription3: `<p>The asset transfer process typically involves:</p><p>i. Identification of the asset and its current ownership details</p><p>ii. Valuation based on book value, fair value, or market price</p><p>iii. Approval through internal finance controls or board resolutions if required</p><p>iv. Documentation such as transfer notes, agreements, or handover reports</p><p>v. Updating records in ERP, accounting systems, and registers</p><p>vi. Compliance with tax or regulatory rules if applicable</p>`,
    relatedBlogs: ["https://www.enkash.com/resources/blog/what-are-fixed-assets", "https://www.enkash.com/resources/blog/what-are-assets-and-liabilities-a-complete-guide", "https://www.enkash.com/resources/blog/fixed-asset-definition-characteristics-and-examples"],
  },
  {
    keyword: `Accounting`,
    slug: `accounting`,
    sheet: `A`,
    definition: `<p>Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.</p>`,
    sectionHeading1: `What is Accounting`,
    sectionDescription1: `<p>Accounting is the systematic process of recording, classifying, summarizing, and reporting a business’s financial transactions to provide accurate information for decision-making, compliance, and financial control.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>For companies in India, accounting ensures accurate tracking of revenue, expenses, assets, liabilities, and taxes in compliance with standards such as Ind AS, Companies Act, and Income Tax Act.</p><p>It forms the financial foundation for budgeting, audits, funding, vendor management, and regulatory reporting.</p>`,
    sectionHeading3: `Key Functions of Accounting`,
    sectionDescription3: `<p>i. Recording - Capturing day-to-day financial activities such as payments, receipts, vendor invoices, reimbursements, and card transactions.</p><p>ii. Classification - Organising entries into ledgers such as assets, liabilities, expenses, income, or equity for accurate analysis.</p><p>iii. Summarisation - Preparing financial statements like the Profit and Loss Statement, Balance Sheet, and Cash Flow Statement.</p><p>iv. Reporting - Presenting financial information to management, auditors, lenders, investors, and regulators.</p><p>v. Reconciliation - Ensuring internal books match external records including bank statements, corporate card data, UPI transactions, and vendor accounts.</p>`,
    relatedBlogs: ["https://www.enkash.com/resources/blog/bookkeeping-vs-accounting-key-differences-every-business-should-know", "https://www.enkash.com/resources/blog/what-is-accounting", "https://www.enkash.com/resources/blog/multi-branch-accounting-software"],
  },
  {
    keyword: `Accounting Cycle`,
    slug: `glossary/accounting-cycle`,
    sheet: `A`,
    definition: `<p>The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.</p>`,
    sectionHeading1: `What is Accounting Cycle`,
    sectionDescription1: `<p>The accounting cycle is the step-by-step process finance teams follow to record, process, and report all financial transactions for a specific accounting period. It ensures books remain accurate, consistent, and audit-ready from start to close.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>The accounting cycle is critical for Indian businesses to stay compliant with Ind AS, GST, TDS, and the Companies Act.</p><p>A disciplined cycle helps finance teams close books on time, maintain clean audit trails, and manage cash flow with confidence. It also reduces manual errors, strengthens internal controls, and supports consistent month-end reporting.</p>`,
    sectionHeading3: `How the Cycle Works`,
    sectionDescription3: `<p>1. Capture Transactions - Identifying all financial activities such as vendor invoices, reimbursements, card spends, bank entries, and revenue events.</p><p>2. Record Journal Entries - Documenting transactions with correct debits and credits in the appropriate journals.</p><p>3. Update Ledger Accounts - Posting journal entries to ledgers like expenses, assets, liabilities, and revenue for organised financial tracking.</p><p>4. Prepare Trial Balance - Ensuring debits and credits match to detect discrepancies early.</p><p>5. Record Adjustments - Adding accruals, prepayments, depreciation, amortisation, and corrections to reflect the actual financial position.</p><p>6. Prepare Adjusted Trial Balance - Validating accuracy after adjustments and ensuring accounts are balanced for reporting.</p><p>7. Generate Financial Statements - Creating the Profit and Loss statement, Balance Sheet, and Cash Flow statement for internal and external stakeholders.</p><p>8. Close the Books - Resetting temporary accounts to start the next accounting period with clean, accurate records.</p>`,
    relatedBlogs: ["https://www.enkash.com/resources/blog/understanding-the-accounting-cycle-importance-steps-and-flowchart", "https://www.enkash.com/resources/blog/what-is-accounting", "https://www.enkash.com/resources/blog/journal-entry-basics-formats-types"],
  },
  {
    keyword: `Accrual Accounting`,
    slug: `glossary/accrual-accounting`,
    sheet: `A`,
    definition: `<p>Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.</p>`,
    sectionHeading1: `Overview`,
    sectionDescription1: `<p>Accrual accounting is a method where income and expenses are recorded when they are earned or incurred, not when cash is received or paid. It reflects the true financial position of a business by matching revenue with related costs.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Accrual accounting is the preferred method for growing businesses, companies governed by the Companies Act, Ind AS filers, and organisations with credit cycles.</p><p>It provides more accurate financial reporting, improves forecasting, and offers better clarity for audits, compliance, and investor reporting.</p>`,
    sectionHeading3: `How it Works`,
    sectionDescription3: `<p>i. Revenue recognition: Recorded when a company delivers goods or services, even if payment is pending.</p><p>ii. Expense recognition: Recorded when costs occur, such as vendor invoices, utilities, or salaries, regardless of payment timing.</p><p>iii. Adjustments: Includes accruals, prepayments, depreciation, and amortization to present accurate period-end results.</p><p>This ensures financial statements reflect economic reality rather than cash movement alone.</p>`,
  },
  {
    keyword: `Accounting Method`,
    slug: `glossary/accounting-method`,
    sheet: `A`,
    definition: `<p>An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.</p>`,
    sectionHeading1: `Overview`,
    sectionDescription1: `<p>An accounting method is the rule a business uses to record income, expenses, and financial activities. It determines when transactions are recognized in the books and how financial performance is reported.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>The accounting method a company chooses affects revenue reporting, tax liability, cash flow visibility, and compliance with Indian standards such as Ind AS and the Income Tax Act.</p><p>For finance teams, choosing the right method ensures consistent books, fewer audit issues, and more reliable decision-making.</p>`,
    sectionHeading3: `Types of Accounting Methods`,
    sectionDescription3: `<p>i. Cash Accounting<br>Records income and expenses only when cash is received or paid. It is best for smaller businesses that want a straightforward view of cash movement.</p><p>ii. Accrual Accounting<br>Records income when earned and expenses when incurred, even if cash moves later. It is used by companies that need accurate reporting, forecasting, and audit readiness.</p><p>iii. Hybrid Method<br>A mix of cash and accrual treatment. It is used in limited cases since Indian tax rules generally prefer consistent use of either cash or accrual.</p>`,
  },
  {
    keyword: `Alternative Minimum Tax (AMT)`,
    slug: `glossary/alternative-maximum-tax`,
    sheet: `A`,
    definition: `<p>Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.</p>`,
    sectionHeading1: `Overview`,
    sectionDescription1: `<p>Alternative Minimum Tax (AMT) is a tax calculation method designed to ensure that taxpayers who claim multiple deductions, exemptions, or incentives still pay a minimum level of tax. It prevents high-income individuals or entities from reducing tax liability disproportionately.</p>`,
    sectionHeading2: `In the Indian Context`,
    sectionDescription2: `<p>AMT applies primarily to non-corporate taxpayers such as LLPs, partnership firms, and individuals or HUFs who claim certain profit-linked deductions under the Income Tax Act.</p><p>It ensures tax parity and restricts aggressive tax planning through incentives.</p>`,
    sectionHeading3: `How AMT Works`,
    sectionDescription3: `<p>In India, Alternative Minimum Tax is applied to ensure that non-corporate taxpayers who claim certain profit-linked deductions still pay a minimum amount of tax.</p><p>Taxpayers must compute tax using both:</p><p>i. Normal Income Tax Provisions</p><p>ii. Alternative Minimum Tax (AMT) using Adjusted Total Income</p><p>The higher of the two becomes the final tax payable.</p>`,
    sectionHeading4: `AMT Rates (India)`,
    sectionDescription4: `<p>i. 18.5% of Adjusted Total Income (standard rate)</p><p>ii. Plus surcharge and health and education cess where applicable</p><p>Note: Rates remain subject to annual Union Budget updates.</p>`,
    relatedBlogs: ["i. 18.5% of Adjusted Total Income (standard rate)\n\nii. Plus surcharge and health and education cess where applicable\n\nNote: Rates remain subject to annual Union Budget updates.", "https://www.enkash.com/resources/blog/guide-on-tds-rate-chart-for-financial-year-2024-2025", "https://www.enkash.com/resources/blog/what-is-gst"],
  },
  {
    keyword: `Audit`,
    slug: `audit`,
    sheet: `A`,
    definition: `<p>An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.</p>`,
    sectionHeading1: `What is Audit`,
    sectionDescription1: `<p>An audit is an independent examination of a company’s financial statements, records, and internal controls to assess whether they present a true and fair view of the organisation’s financial position.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Audits help Indian businesses meet statutory requirements under the Companies Act, Income Tax Act, GST laws, and other regulatory frameworks.</p><p>They strengthen financial discipline, ensure transparency, and build trust with investors, lenders, auditors, customers, and internal stakeholders.</p>`,
    sectionHeading3: `Types of Audits`,
    sectionDescription3: `<p>i. Statutory Audit - Mandatory review of financial statements for companies and certain entities as per the Companies Act.</p><p>ii. Internal Audit - Ongoing assessment of internal controls, processes, and risk systems to ensure operational efficiency.</p><p>iii. Tax Audit - Required under Section 44AB of the Income Tax Act for businesses above specified turnover thresholds.</p><p>iv. GST Audit - Review of GST filings, input tax credit, and compliance accuracy (applicable under certain turnover limits or notices).</p><p>v. Special / Compliance Audits - Audits ordered by regulators, lenders, or investors to examine specific areas like expenses, systems, or governance.</p>`,
  },
  {
    keyword: `Audit Risk`,
    slug: `glossary/audit-risk`,
    sheet: `A`,
    definition: `<p>Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.</p>`,
    sectionHeading1: `What is Audit Risk`,
    sectionDescription1: `<p>Audit risk is the possibility that an auditor may issue an incorrect opinion on a company’s financial statements, typically by concluding that the statements are accurate when they contain material misstatements.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Audit risk is a critical concept for Indian businesses subject to statutory audits under the Companies Act, 2013, Income Tax Act, or GST regulations.</p><p>It influences audit planning, internal controls, and the accuracy of financial reporting.</p><p>A high audit risk can lead to regulatory penalties, restatements, reputational damage, or compliance gaps.</p>`,
    sectionHeading3: `Why Audit Risk Matters for Businesses`,
    sectionDescription3: `<p>i. Ensures financial statements reflect true and fair information.</p><p>ii. Strengthens internal controls and reduces operational leakages.</p><p>iii. Minimizes chances of penalties, tax notices, or compliance findings.</p><p>iv. Builds trust with investors, auditors, banks, and stakeholders.</p><p>v. Helps finance teams design better documentation and approval processes.</p>`,
  },
  {
    keyword: `AML (Anti-Money Laundering)`,
    slug: `glossary/anti-money-laundering`,
    sheet: `A`,
    definition: `<p>AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.</p>`,
    sectionHeading1: `Definition`,
    sectionDescription1: `<p>AML refers to a set of laws, regulations, and processes designed to prevent criminals from disguising illegally obtained funds as legitimate money. It ensures that financial systems are not used for fraud, terrorism financing, or unlawful activities.</p>`,
    sectionHeading2: `Regulatory Context`,
    sectionDescription2: `<p>AML is a critical part of India’s financial and regulatory environment. Banks, fintechs, payment aggregators, PPIs, and businesses handling financial transactions must comply with AML norms issued by:</p><p>i. RBI (Reserve Bank of India)</p><p>ii. FIU-IND (Financial Intelligence Unit – India)</p><p>iii. Prevention of Money Laundering Act (PMLA)</p><p>iv. SEBI, IRDAI, and sector regulators</p><p>Strong AML practices protect businesses from legal penalties, reputational damage, operational risk, and disruptions in payment flows.</p>`,
    sectionHeading3: `What AML Includes`,
    sectionDescription3: `<p>1. KYC (Know Your Customer)<br>Verifying the identity and legitimacy of customers before onboarding.</p><p>2. CDD & Enhanced Due Diligence<br>Assessing customer risk and applying deeper checks for high-risk customers.</p><p>3. Transaction Monitoring<br>Detecting unusual spending patterns, large cash movements, or suspicious activities.</p><p>4. Screening<br>Checking customers against sanction lists, watchlists, negative media, and PEP (Politically Exposed Persons) databases.</p><p>5. Reporting<br>Filing mandatory reports to FIU-IND such as STRs (Suspicious Transaction Reports) or CTRs (Cash Transaction Reports).</p><p>6. Record Keeping<br>Maintaining KYC and transaction logs for regulatory audit and examinations.</p>`,
  },
  {
    keyword: `Business Expenses`,
    slug: `business-expense`,
    sheet: `B`,
    definition: `<p><a href="http://localhost:3000/glossary/b/billing-cycle" target="_blank" rel="noopener noreferrer">Business expenses are the costs an organisation incurs to operate, deliver services, support employees, and generate revenue. These include vendor payments, travel and meal spends, utilities, subscriptions, marketing, payroll-related costs, and other day-to-day operational expenses.</a></p>`,
    sectionHeading1: `What are Business Expenses`,
    sectionDescription1: `<p><a href="http://localhost:3000/glossary/b/billing-cycle" target="_blank" rel="noopener noreferrer">Business expenses are the costs an organisation incurs to operate, deliver services, support employees, and generate revenue. These include vendor payments, travel and meal spends, utilities, subscriptions, marketing, payroll-related costs, and other day-to-day operational expenses.</a></p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Business expenses form the foundation of financial planning, cost control, and compliance.</p><p>For Indian companies, accurate expense tracking is essential for budgeting, GST input tax credit, TDS management, statutory audits, and Ind AS reporting.</p><p>They help finance teams understand spending patterns, maintain cost discipline, and identify areas where operational efficiency can improve.</p>`,
    sectionHeading3: `How Business Expenses Work`,
    sectionDescription3: `<p>Business expenses are generally grouped into key categories such as:</p><p>i. Operating expenses (utilities, rent, salaries, technology, marketing)</p><p>ii. Administrative expenses (HR, finance, compliance costs)</p><p>iii. Employee expenses (travel, meals, fuel, out-of-pocket payments)</p><p>iv. Procurement & vendor expenses (goods and services purchased from suppliers)</p><p>v. Project-based or departmental expenses (budgeted team spending)</p><p>Expenses must be:</p><p>i. Recorded when incurred</p><p>ii. Classified under the correct ledger</p><p>iii. Supported with documentation</p><p>iv. Approved as per internal policies</p><p>v. Reconciled against bank and card transactions</p><p>Finance teams rely on clean expense data for month-end close, cost allocation, audit trails, and accurate financial reporting.</p>`,
  },
  {
    keyword: `Billing Cycle`,
    slug: `billing-cycle`,
    sheet: `B`,
    definition: `<p><a href="https://www.enkash.com/resources/blog/what-is-billing-2" target="_blank" rel="noopener noreferrer">A billing cycle is the fixed period during which all transactions, expenses, or charges are recorded before a statement is generated. It defines the start and end dates for calculating dues, payments, and reconciliations for cards, subscriptions, utility bills, or vendor invoices.</a></p>`,
    sectionHeading1: `What is Billing Cycle`,
    sectionDescription1: `<p><a href="https://www.enkash.com/resources/blog/what-is-billing-2" target="_blank" rel="noopener noreferrer">A billing cycle is the fixed period during which all transactions, expenses, or charges are recorded before a statement is generated. It defines the start and end dates for calculating dues, payments, and reconciliations for cards, subscriptions, utility bills, or vendor invoices.</a></p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>In corporate finance, the billing cycle plays a critical role in cash flow forecasting, payment planning, and reconciliation.</p><p>For businesses using corporate cards, prepaid cards, SaaS tools, and utilities, billing cycles determine when expenses appear, when payments are due, and how spend is accounted for during month-end close.</p><p>A clearly defined billing cycle helps finance teams maintain predictable schedules for approvals, expense reporting, audits, and payment processing.</p>`,
    sectionHeading3: `How Billing Cycles Work`,
    sectionDescription3: `<p>A billing cycle groups all transactions made within a defined period (e.g., 1st–30th).<br>At the end of the cycle:</p><p>i. A statement is generated summarising all transactions</p><p>ii. A due date is assigned for settlement</p><p>iii. Finance teams reconcile expenses with supporting records</p><p>iv. The cycle resets for the next period</p><p>Billing cycles may be monthly, weekly, or customised depending on the product or service provider.</p>`,
  },
  {
    keyword: `Budgeting`,
    slug: `budgeting`,
    sheet: `B`,
    definition: `<p>Budgeting is the process of planning and allocating financial resources across departments, projects, and activities to ensure that spending supports business goals and remains within approved limits.</p>`,
    sectionHeading1: `Definition`,
    sectionDescription1: `<p>Budgeting is the process of planning and allocating financial resources across departments, projects, and activities to ensure that spending supports business goals and remains within approved limits.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Budgeting is central to how organisations manage costs, control spending, and plan for growth.</p><p>For Indian businesses, effective budgeting ensures compliance with financial policies, supports statutory reporting, and enables better operational decision-making.</p><p>It helps finance teams anticipate expenses, track performance against targets, and maintain financial discipline across departments and cost centres.</p>`,
    sectionHeading3: `How Budgeting Works`,
    sectionDescription3: `<p>Budgeting typically involves:</p><p>i. Setting financial targets based on revenue forecasts and strategic priorities</p><p>ii. Allocating budgets to teams such as marketing, operations, HR, sales, or procurement</p><p>iii. Defining spending limits for categories, vendors, and cost centres</p><p>iv. Monitoring expenses against budgeted amounts throughout the financial period</p><p>v. Making adjustments as business needs evolve or actual spending varies</p><p>Budgets may be annual, quarterly, monthly, or project-specific, depending on organisational structure.</p>`,
  },
  {
    keyword: `Bill of Exchange`,
    slug: `bill-of-exchange`,
    sheet: `B`,
    definition: `<p>A Bill of Exchange is a written, legally binding document that instructs one party to pay a fixed amount to another party at a predetermined date. It is commonly used in trade, procurement, credit sales, and business-to-business transactions to formalise payment obligations.</p>`,
    sectionHeading1: `What is a Bill of Exchange?`,
    sectionDescription1: `<p>A Bill of Exchange is a written, legally binding document that instructs one party to pay a fixed amount to another party at a predetermined date. It is commonly used in trade, procurement, credit sales, and business-to-business transactions to formalise payment obligations.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Bills of Exchange are widely used in Indian and international trade to provide clarity, trust, and structure in credit-based transactions.</p><p>They serve as negotiable instruments under the Negotiable Instruments Act, 1881, helping businesses document receivables, secure payments, and reduce disputes.</p><p>For finance teams, Bills of Exchange support better cash flow planning, accounts receivable management, and formalisation of vendor or customer obligations.</p>`,
    sectionHeading3: `How a Bill of Exchange Works`,
    sectionDescription3: `<p>A Bill of Exchange involves three parties:</p><p>i. Drawer – The person/entity who issues the bill and demands payment</p><p>ii. Drawee – The person/entity who is required to pay</p><p>iii. Payee – The person/entity who will receive the payment</p><p>The process typically involves:</p><p>i. The drawer issues the bill stating the amount, payee, and due date.</p><p>ii. The drawee accepts the bill, acknowledging the obligation to pay.</p><p>iii. The bill matures on the due date, and the drawee settles the payment.</p><p>Bills can be used for immediate payment (sight bills) or future-dated payment (usance bills).</p>`,
  },
  {
    keyword: `Bucketing`,
    slug: `bucketing`,
    sheet: `B`,
    definition: `<p>Bucketing is the process of grouping transactions, expenses, customers, risks, or financial data into predefined categories to improve analysis, reporting, and decision-making. It enables organisations to classify information in a structured and consistent way.</p>`,
    sectionHeading1: `Definition`,
    sectionDescription1: `<p>Bucketing is the process of grouping transactions, expenses, customers, risks, or financial data into predefined categories to improve analysis, reporting, and decision-making. It enables organisations to classify information in a structured and consistent way.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Bucketing is widely used in finance, accounting, risk management, spend control, and data analytics.</p><p>For organisations handling large volumes of transactions, such as payments, expenses, vendor invoices, or receivables, bucketing helps standardise classification, improve visibility, and support accurate reporting.</p><p>Finance teams rely on bucketing to analyse spending patterns, track category-wise budgets, detect anomalies, and maintain compliance across internal and statutory processes.</p>`,
    sectionHeading3: `How Bucketing Works`,
    sectionDescription3: `<p>Bucketing involves assigning each transaction or data point to a relevant category based on rules, attributes, or behaviour.</p><p>This may include grouping by:</p><p>i. Expense category (travel, meals, utilities, software)</p><p>ii. Transaction type (card payments, reimbursements, vendor invoices)</p><p>iii. Risk level (low, medium, high in AML or credit scoring)</p><p>iv. Ageing (0–30, 31–60, 61–90 days for receivables or payables)</p><p>v. Department or cost centre</p><p>vi. Vendor or project</p><p>Bucketing can be rule-based, automated, or AI-driven, depending on the platform.</p>`,
  },
  {
    keyword: `Bill of Lading`,
    slug: `bill-of-lading`,
    sheet: `B`,
    definition: `<p>A Bill of Lading (BoL) is a legally binding document issued by a carrier to a shipper, serving as proof of shipment, a receipt of goods, and a document of title. It confirms the type, quantity, and destination of goods being transported and is essential for both domestic and international trade.</p>`,
    sectionHeading1: `What is a Bill of Lading`,
    sectionDescription1: `<p>A Bill of Lading (BoL) is a legally binding document issued by a carrier to a shipper, serving as proof of shipment, a receipt of goods, and a document of title. It confirms the type, quantity, and destination of goods being transported and is essential for both domestic and international trade.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>In procurement, supply chain, and cross-border trade, the Bill of Lading acts as the primary document that validates a shipment’s movement and ownership.</p><p>It enables businesses to verify that goods have been dispatched, track their movement, and initiate payments to suppliers or logistics partners.</p><p>For finance teams, a BoL is a key supporting document for vendor payments, GST compliance, import/export documentation, and audit trails.</p>`,
    sectionHeading3: `How a Bill of Lading Works`,
    sectionDescription3: `<p>A BoL operates as three documents in one:</p><p>i. Shipment Receipt – Confirms the carrier has received the goods.</p><p>ii. Contract of Carriage – Defines the terms under which goods will be transported.</p><p>iii. Document of Title – Indicates ownership of the goods and may be used to transfer title.</p><p>The process typically includes:</p><p>i. Shipper hands goods to the carrier</p><p>ii. Carrier issues the Bill of Lading</p><p>iii. BoL accompanies the cargo or is shared electronically</p><p>iv. Consignee presents the BoL to claim the goods</p><p>v. Finance team processes vendor payment based on BoL and invoice</p>`,
  },
  {
    keyword: `Business Cycle`,
    slug: `business-cycle`,
    sheet: `B`,
    definition: `<p>The business cycle refers to the natural rise and fall of economic activity over time. It consists of periods of expansion and contraction that affect output, employment, investments, consumer spending, and business performance across an economy.</p>`,
    sectionHeading1: `What Is the Business Cycle`,
    sectionDescription1: `<p>The business cycle refers to the natural rise and fall of economic activity over time. It consists of periods of expansion and contraction that affect output, employment, investments, consumer spending, and business performance across an economy.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Business cycles influence company revenues, borrowing costs, hiring decisions, and investment plans.</p><p>During economic expansion, businesses typically increase production, spending, and hiring.</p><p>During contraction or recession, companies reduce costs, delay investments, and focus on efficiency and cash flow.</p><p>For finance teams, understanding the business cycle is essential for forecasting, budget planning, risk management, and long-term decision-making.</p>`,
    sectionHeading3: `Key Stages of the Business Cycle`,
    sectionDescription3: `<p>1. Expansion - Rising output, higher demand, business investment, job growth, and improved consumer confidence.</p><p>2. Peak - The economy reaches maximum output; inflationary pressure often rises.</p><p>3. Contraction (or Recession) - Falling demand, reduced production, layoffs, lower business investment, and declining cash flow.</p><p>4. Trough - The lowest point of economic activity before recovery begins.</p><p>5. Recovery - Economic activity picks up, spending stabilises, and businesses begin investing again.</p>`,
  },
  {
    keyword: `Bharat Bill Payment System (BBPS)`,
    slug: `bharat-bill-payment-system`,
    sheet: `B`,
    definition: `<p>The Bharat Bill Payment System (BBPS) is an RBI-regulated, NPCI-operated interoperable bill payment ecosystem that enables customers to pay recurring bills, such as electricity, water, gas, telecom, loan EMIs, FASTag recharge, and more, through a unified and standardised platform. It ensures secure, consistent, and real-time bill payments across banks, fintechs, and digital payment apps.</p>`,
    sectionHeading1: `Definition`,
    sectionDescription1: `<p>The Bharat Bill Payment System (BBPS) is an RBI-regulated, NPCI-operated interoperable bill payment ecosystem that enables customers to pay recurring bills, such as electricity, water, gas, telecom, loan EMIs, FASTag recharge, and more, through a unified and standardised platform. It ensures secure, consistent, and real-time bill payments across banks, fintechs, and digital payment apps.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>BBPS simplifies bill payments for individuals and businesses by providing a single, integrated system for managing recurring payments.</p><p>For organisations, especially those with multiple offices, utility vendors, and repeating operational expenses, BBPS ensures:</p><p>i. Standardised payment experience</p><p>ii. Instant confirmations</p><p>iii. Reliable reconciliation</p><p>iv. Regulatory compliance</p><p>It reduces manual effort, improves audit trails, and centralises bill payment workflows.</p>`,
    sectionHeading3: `How BBPS Works`,
    sectionDescription3: `<p>BBPS operates through four key entities:</p><p>i. Biller – The service provider generating the bill</p><p>ii. Customer – The payer</p><p>iii. Biller Operating Unit (BOU) – Entity onboarding billers</p><p>iv. Customer Operating Unit (COU) – Entity offering BBPS bill payments to users</p><p>The process includes:</p><p>i. Customer initiates bill payment via a BBPS-enabled app or platform</p><p>ii. BBPS fetches real-time bill details from the biller</p><p>iii. Customer pays using any supported payment mode</p><p>iv. Payment confirmation and receipt are generated instantly</p><p>v. NPCI ensures settlement between the parties</p>`,
  },
  {
    keyword: `Balance of Payments (BOP)`,
    slug: `balance-of-payment`,
    sheet: `B`,
    definition: `<p>The Balance of Payments (BOP) is a comprehensive financial statement that records all economic transactions between a country and the rest of the world during a specific period. It shows the flow of money into and out of a country through trade, investments, services, remittances, and financial transfers.</p>`,
    sectionHeading1: `What is Balance of Payments?`,
    sectionDescription1: `<p>The Balance of Payments (BOP) is a comprehensive financial statement that records all economic transactions between a country and the rest of the world during a specific period. It shows the flow of money into and out of a country through trade, investments, services, remittances, and financial transfers.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>The BOP helps governments, central banks, and businesses understand a country’s economic position and external stability.</p><p>A positive BOP indicates more money flowing into the country than going out, while a negative BOP suggests the opposite.</p><p>For companies, especially those involved in exports, imports, international investments, or cross-border supply chains, BOP trends influence:</p><p>i. Currency movements</p><p>ii. Interest rates</p><p>iii. Trade policies</p><p>iv. Market demand</p><p>v. Capital flows</p><p>Understanding BOP helps businesses anticipate economic conditions that may affect pricing, demand, borrowing costs, and global expansion plans.</p>`,
    sectionHeading3: `Key Components of the Balance of Payments`,
    sectionDescription3: `<p>1. Current Account - Tracks trade in goods and services, income flows (interest, dividends), and transfers (remittances, aid).<br>It shows whether a country is a net importer or exporter.</p><p>2. Capital Account - Records capital transfers, foreign asset transactions, and the sale or purchase of fixed assets such as real estate.</p><p>3. Financial Account - Captures cross-border investments including FDI (foreign direct investment), FPI (foreign portfolio investment), loans, and banking flows.</p><p>Together, these accounts determine whether the country’s external position is in surplus or deficit.</p>`,
  },
  {
    keyword: `Balance Sheet`,
    slug: `balance-sheet`,
    sheet: `B`,
    definition: `<p><a href="https://www.enkash.com/resources/blog/balance-sheet-meaning-formula-importance" target="_blank" rel="noopener noreferrer">A Balance Sheet is a financial statement that shows a company’s assets, liabilities, and shareholders’ equity at a specific point in time.<br>It provides a snapshot of what the business owns, what it owes, and the net value attributable to its owners.</a></p>`,
    sectionHeading1: `What is a Balance Sheet`,
    sectionDescription1: `<p><a href="https://www.enkash.com/resources/blog/balance-sheet-meaning-formula-importance" target="_blank" rel="noopener noreferrer">A Balance Sheet is a financial statement that shows a company’s assets, liabilities, and shareholders’ equity at a specific point in time.<br>It provides a snapshot of what the business owns, what it owes, and the net value attributable to its owners.</a></p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>The Balance Sheet is one of the core financial statements used by management, investors, lenders, and auditors to assess a company’s financial health. It helps businesses understand liquidity, leverage, working capital, and long-term solvency.</p><p>Finance teams rely on the Balance Sheet to support budgeting, compliance, capital planning, audit preparation, and internal decision-making. It also directly affects creditworthiness, funding access, and valuation.</p>`,
    sectionDescription3: `<p>1. Assets</p><p>Resources owned by the company. It includes cash, receivables, inventory, equipment, property, and investments. Divided into:</p><p>i. Current Assets (short-term)</p><p>ii. Non-Current Assets (long-term)</p><p>2. Liabilities</p><p>Obligations the company must repay. It includes payables, loans, accrued expenses, lease liabilities, and other debts. Divided into:</p><p>i. Current Liabilities</p><p>ii. Non-Current Liabilities</p><p>3. Shareholders’ Equity</p><p>The owners’ residual interest in the company after liabilities are deducted from assets. It includes share capital, retained earnings, reserves, and accumulated profits.</p><p>The core equation: Assets = Liabilities + Equity</p>`,
  },
  {
    keyword: `Corporate Card`,
    slug: `corporate-card`,
    sheet: `C`,
    definition: `<p>A corporate card is a business-issued payment card used by employees to pay for authorised work-related expenses such as travel, meals, fuel, subscriptions, utilities, and operational purchases. It centralises company spending, improves visibility, and simplifies tracking and reconciliation for finance teams.</p>`,
    sectionHeading1: `What Is a Corporate Card`,
    sectionDescription1: `<p>A corporate card is a business-issued payment card used by employees to pay for authorised work-related expenses such as travel, meals, fuel, subscriptions, utilities, and operational purchases. It centralises company spending, improves visibility, and simplifies tracking and reconciliation for finance teams.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Corporate cards help organisations manage employee and departmental spending more efficiently. Instead of out-of-pocket payments and manual reimbursements, cards provide:</p><p>1. Controlled access to company funds</p><p>2. Real-time transaction visibility</p><p>3. Clear audit trails</p><p>4. Category-level restrictions</p><p>5. Easier reconciliations for month-end close</p><p>They are widely used across finance, sales, operations, procurement, admin, and field teams.</p>`,
    sectionHeading3: `How Corporate Cards Work`,
    sectionDescription3: `<p>Employees receive cards with predefined limits, categories, and policies set by the finance team. When used for business expenses:</p><p>i. Transactions are logged instantly</p><p>ii. Controls block unauthorised spending</p><p>iii. Digital receipts can be attached</p><p>iv. Approvals follow a pre-set workflow</p><p>v. Expenses sync with accounting and ERP tools</p><p>Corporate cards can be prepaid, credit, or expense-only depending on company policy and regulatory framework.</p>`,
    sectionHeading4: `Types of Corporate Cards`,
    sectionDescription4: `<p>1. Prepaid Corporate Cards</p><p>Loaded with a predefined balance. Ideal for controlled spending.</p><p>2. Credit Corporate Cards</p><p>Issued with a credit line. Suitable for larger organisations with predictable spending habits.</p><p>3. Category-Specific Cards</p><p>Purpose-built cards such as:</p><p>i. Travel cards</p><p>ii. Meal cards</p><p>iii. Fuel cards</p><p>iv. Purchase cards</p><p>v. Marketing cards</p><p>4. Virtual Cards</p><p>Instant, one-time or multi-use digital cards for subscriptions, online vendor payments, and secure transactions.</p>`,
    sectionHeading5: `How EnKash Helps`,
    sectionDescription5: `<p>EnKash offers one of India’s most advanced corporate card infrastructures, purpose-built for complete control, compliance, and visibility.</p><p>From prepaid cards to virtual and category-specific cards, every spend is tracked in real time, governed by policy-level controls, and reconciled automatically.</p><p>Finance teams manage all company-wide spending from a single, intelligent platform designed to eliminate leakage, simplify audits, and accelerate month-end close.</p>`,
  },
  {
    keyword: `Cash Flow`,
    slug: `cash-flow`,
    sheet: `C`,
    definition: `<p>Cash flow refers to the movement of money into and out of a business over a specific period. It shows how much cash a company generates and uses through its operating, investing, and financing activities.</p>`,
    sectionHeading1: `What Is Cash Flow`,
    sectionDescription1: `<p>Cash flow refers to the movement of money into and out of a business over a specific period. It shows how much cash a company generates and uses through its operating, investing, and financing activities.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Cash flow is a core indicator of a company’s financial health, liquidity, and ability to meet short-term obligations. Strong cash flow enables businesses to pay vendors on time, invest in growth, manage payroll, and handle unexpected expenses. Limited or irregular cash flow can lead to operational delays, borrowing dependency, or disruptions in vendor and employee payments.</p><p>Finance teams track cash flow closely to plan budgets, optimise working capital, ensure timely settlements, and forecast future liquidity needs.</p>`,
    sectionHeading3: `Types of Cash Flow`,
    sectionDescription3: `<p>1. Operating Cash Flow (OCF) - Cash generated from core business operations such as sales collections and payments to suppliers.</p><p>2. Investing Cash Flow - Cash used for or received from investments in assets, equipment, or long-term projects.</p><p>3. Financing Cash Flow - Cash related to borrowing, repaying loans, issuing shares, or paying dividends.</p><p>4. Free Cash Flow (FCF) - The cash remaining after covering operating expenses and capital expenditures, an indicator of financial flexibility.</p>`,
    sectionHeading4: `How Cash Flow Works`,
    sectionDescription4: `<p>Cash flow is tracked through actual cash movements, not just accounting entries. It typically includes:</p><p>1. Cash inflows: revenue, collections, loans, asset sales</p><p>2. Cash outflows: vendor payments, payroll, utilities, loan repayments, CapEx</p><p>Positive cash flow (inflows > outflows) strengthens liquidity.</p><p>Negative cash flow (outflows > inflows) raises concerns around sustainability, working capital, and payment cycles.</p><p>Finance teams use cash flow statements to analyse trends, compare performance with forecasts, and make strategic decisions on spending, investments, and credit.</p>`,
  },
  {
    keyword: `Chargeback`,
    slug: `charge-back`,
    sheet: `C`,
    definition: `<p>A chargeback is a payment reversal initiated by the cardholder’s bank when a customer disputes a transaction. The disputed amount is pulled back from the merchant and returned to the customer after review. Chargebacks protect customers from fraud, unauthorised payments, or billing errors but can impact a business’s revenue and risk profile.</p>`,
    sectionHeading1: `Definition`,
    sectionDescription1: `<p>A chargeback is a payment reversal initiated by the cardholder’s bank when a customer disputes a transaction. The disputed amount is pulled back from the merchant and returned to the customer after review. Chargebacks protect customers from fraud, unauthorised payments, or billing errors but can impact a business’s revenue and risk profile.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Chargebacks are a standard mechanism in card payments - credit, debit, and prepaid. For businesses, frequent chargebacks signal operational issues such as dispute management gaps, poor documentation, misleading charges, or fraud exposure.</p><p>Merchants may face:</p><p>i. Revenue loss</p><p>ii. Penalties from card networks</p><p>iii. Higher transaction scrutiny</p><p>iv. Operational overhead to respond to disputes</p><p>For finance teams, managing chargebacks requires strong evidence collection, invoice and transaction matching, and timely responses to issuing banks.</p>`,
    sectionHeading3: `How Chargebacks Work`,
    sectionDescription3: `<p>A chargeback typically follows these steps:</p><p>i. Customer raises a dispute with their issuing bank.</p><p>ii. The issuing bank reviews the claim and temporarily reverses the amount.</p><p>iii. The acquiring bank notifies the merchant to provide supporting documents.</p><p>iv. The merchant submits proof such as invoices, delivery confirmation, or transaction logs.</p><p>v. Card networks evaluate the evidence and take a decision.</p><p>vi. The dispute is either resolved in the merchant’s favour or refunded to the customer.</p><p>Chargebacks may arise due to fraud, duplicate charges, service issues, unauthorised payments, or technical errors.</p>`,
    sectionHeading4: `Reasons for Chargebacks`,
    sectionDescription4: `<p>1. Fraudulent Transactions - Unauthorised use of the customer’s card.</p><p>2. Duplicate or Incorrect Charges - Multiple payments, wrong amount, or processing errors.</p><p>3. Product or Service Disputes - Item not delivered, defective, or not as described.</p><p>4. Technical Errors - System issues like failed reversals or delayed authorisations.</p><p>5. Friendly Fraud - Customers raise disputes despite legitimate transactions.</p>`,
  },
  {
    keyword: `Cash Ratio`,
    slug: `cash-ratio`,
    sheet: `C`,
    definition: `<p>The cash ratio measures a company’s ability to meet its short-term liabilities using only its most liquid assets - cash and cash equivalents. It shows how quickly a business can pay off immediate obligations without relying on receivables or inventory.</p><p>Formula:<br>Cash Ratio = (Cash + Cash Equivalents) / Current Liabilities</p>`,
    sectionHeading1: `What is Cash Ratio`,
    sectionDescription1: `<p>The cash ratio measures a company’s ability to meet its short-term liabilities using only its most liquid assets - cash and cash equivalents. It shows how quickly a business can pay off immediate obligations without relying on receivables or inventory.</p><p>Formula:<br>Cash Ratio = (Cash + Cash Equivalents) / Current Liabilities</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>The cash ratio is one of the strictest liquidity indicators used by lenders, investors, and finance teams. It reflects how well a company can handle short-term obligations such as vendor payments, loan instalments, utility bills, and operational expenses.</p><p>A higher cash ratio signals strong liquidity and financial stability. A very low ratio may indicate cash shortages or dependence on external funding.</p><p>Finance teams analyse the cash ratio to ensure smooth operations, maintain working capital, and plan short-term cash needs responsibly.</p>`,
    sectionHeading3: `How Cash Ratio Works`,
    sectionDescription3: `<p>The cash ratio considers only the most liquid assets:</p><p>i. Cash on hand</p><p>ii. Bank balances</p><p>iii. Cash equivalents (short-term investments easily converted to cash)</p><p>It excludes:</p><p>i. Inventory</p><p>ii. Accounts receivable</p><p>iii. Prepaid expenses</p><p>Because of this strict measurement, the cash ratio offers a conservative view of liquidity that helps businesses prepare for immediate cash commitments.</p>`,
    sectionHeading4: `Interpreting the Cash Ratio`,
    sectionDescription4: `<p>1. Cash Ratio < 1</p><p>The company does not have enough cash to cover short-term liabilities. It suggests liquidity stress; requires tighter cash flow management.</p><p>2. Cash Ratio = 1</p><p>Cash perfectly matches short-term liabilities. It indicates stable liquidity.</p><p>3. Cash Ratio > 1</p><p>Company holds more cash than required. Positive, but excess idle cash may affect returns.</p>`,
  },
  {
    keyword: `Currency Risk`,
    slug: `currency-risk`,
    sheet: `C`,
    definition: `<p>Currency risk, also known as exchange rate risk, is the possibility of financial loss caused by fluctuations in foreign currency exchange rates. It affects businesses that import, export, borrow, invest, or make payments in foreign currencies.</p>`,
    sectionHeading1: `What is Currency Risk`,
    sectionDescription1: `<p>Currency risk, also known as exchange rate risk, is the possibility of financial loss caused by fluctuations in foreign currency exchange rates. It affects businesses that import, export, borrow, invest, or make payments in foreign currencies.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Currency movements directly impact cross-border payments, vendor invoices, international purchases, foreign investments, and revenue earned in overseas markets. For companies dealing with USD, EUR, GBP, AED, or any other currency, sudden fluctuations can increase costs or reduce margins.</p><p>Finance teams monitor currency risk closely to manage:</p><p>i. International vendor payments</p><p>ii. Foreign currency receivables</p><p>iii. Overseas payroll or branch expenses</p><p>iv. Import-export pricing</p><p>v. Debt repayments tied to foreign currency</p><p>Managing this risk is essential for protecting profitability and maintaining pricing stability.</p>`,
    sectionHeading3: `Types of Currency Risk`,
    sectionDescription3: `<p>1. Transaction Risk - Risk arising from actual cross-border payments - imports, exports, or international invoices.</p><p>2. Translation Risk - Impact of converting foreign subsidiary financials into the home currency for reporting.</p><p>3. Economic Risk - Long-term impact on a company’s competitiveness due to currency changes affecting demand, pricing, or sourcing plans.</p>`,
    sectionDescription4: `<p>Currency risk arises because exchange rates change constantly based on macroeconomic and market factors such as interest rates, inflation, global sentiment, geopolitical events, and central bank actions.</p><p>When these movements turn unfavourable, the cost of foreign currency transactions increases, making imports more expensive, reducing export margins, raising the cost of servicing foreign-currency loans, and affecting the value of overseas revenue.</p><p>To manage this volatility, businesses often use hedging tools such as forward contracts, structured payment timings, and pricing adjustments to protect margins and stabilise cash flow.</p>`,
  },
  {
    keyword: `Counterparty Risk`,
    slug: `counterparty-risk`,
    sheet: `C`,
    definition: `<p>Counterparty risk is the possibility that the other party in a financial transaction will fail to meet their obligations, either by defaulting, delaying payment, or not delivering what was contractually agreed. It exists in transactions such as loans, vendor payments, derivatives, cross-border deals, and credit-based arrangements.</p>`,
    sectionHeading1: `What is Counterparty Risk`,
    sectionDescription1: `<p>Counterparty risk is the possibility that the other party in a financial transaction will fail to meet their obligations, either by defaulting, delaying payment, or not delivering what was contractually agreed. It exists in transactions such as loans, vendor payments, derivatives, cross-border deals, and credit-based arrangements.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Every business engages with multiple counterparties - vendors, lenders, customers, banks, investors, and service providers. If any counterparty fails to honour its obligation, the company faces financial loss, delays, operational disruption, or liquidity pressure.</p><p>Counterparty risk is especially relevant in:</p><p>i. Credit sales</p><p>ii. Vendor payments</p><p>iii. Lending and borrowing</p><p>iv. Derivative contracts</p><p>v. Cross-border settlements</p><p>vi.Supply chain partnerships</p><p>Finance teams evaluate this risk to protect cash flow, ensure business continuity, and maintain reliable commercial relationships.</p>`,
    sectionHeading3: `Types of Counterparty Risk`,
    sectionDescription3: `<p>1. Credit Risk - Risk that the counterparty cannot repay loans, invoices, or credit dues.</p><p>2. Settlement Risk - Risk that one party delivers payment or goods, but the other party fails to reciprocate.</p><p>3. Market-Linked Counterparty Risk - Risk arising in financial markets where the counterparty may default due to adverse price movements (common in derivatives).</p><p>4. Operational Counterparty Risk - Risk caused by process failures, fraud, system issues, or mismanagement at the counterparty’s end.</p>`,
    sectionHeading4: `How Counterparty Risk Works`,
    sectionDescription4: `<p>Counterparty risk emerges when one party relies on another to fulfil a financial obligation. It is influenced by:</p><p>i. Financial strength of the counterparty</p><p>ii. Credit history and repayment behaviour</p><p>iii. Liquidity and cash flow position</p><p>iv. Market conditions or volatility</p><p>v. Geopolitical events</p><p>vi. Operational capabilities (fraud control, systems, processes)</p><p>Businesses mitigate this risk through credit checks, contracts, collateral, advance payments, payment terms, guarantees, or diversification of suppliers and partners.</p>`,
  },
  {
    keyword: `Credit Note`,
    slug: `credit-note`,
    sheet: `C`,
    definition: `<p>A credit note is a document issued by a seller to adjust the value of a previously issued invoice. It is used when the billed amount was incorrect, goods were returned, services were cancelled, or GST was charged wrongly. A credit note reduces the seller’s revenue and the buyer’s outstanding payable for that transaction and ensures that both parties’ books reflect the correct taxable value.</p>`,
    sectionHeading1: `What is Credit Note`,
    sectionDescription1: `<p>A credit note is a document issued by a seller to adjust the value of a previously issued invoice. It is used when the billed amount was incorrect, goods were returned, services were cancelled, or GST was charged wrongly. A credit note reduces the seller’s revenue and the buyer’s outstanding payable for that transaction and ensures that both parties’ books reflect the correct taxable value.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Credit notes are a key part of financial accuracy, GST compliance, and customer transparency. They help businesses correct overbilling, manage returns, update tax calculations, and maintain clean accounting records.</p><p>Common reasons include:</p><p>i. Wrong quantity or price on the invoice</p><p>ii. Incorrect GST rate applied</p><p>iii. Goods returned or services cancelled</p><p>iv. Post-invoice discounts or adjustments</p><p>v. Duplicate or excess billing</p><p>For finance teams, credit notes ensure proper reconciliation, accurate ledger balances, and alignment between invoices, vendor statements, and GST filings.</p>`,
    sectionHeading3: `How Credit Notes Work`,
    sectionDescription3: `<p>When an issued invoice contains an error or needs a value reduction, the seller generates a credit note with details such as invoice number, revised amount, reason, and tax adjustment.</p><p>The credit note:</p><p>i. Reduces the original invoice value</p><p>ii. Updates accounts receivable/payable</p><p>iii. Adjusts GST liability in the relevant tax period</p><p>iv. Ensures the buyer's payable reduces accordingly</p><p>v. Creates a clear audit trail for compliance</p><p>In GST, credit notes must be reported in GSTR-1 and are reconciled by the buyer through GSTR-2B/2A.</p>`,
  },
  {
    keyword: `Card Tokenization`,
    slug: `card-tokenization`,
    sheet: `C`,
    definition: `<p>Card tokenization is a security process that replaces a customer’s actual card number (PAN) with a randomly generated, unique token during digital payments. This token can be used for transactions instead of storing or sharing sensitive card data, reducing exposure to fraud. In India, tokenization is mandated and regulated by the RBI for all card-on-file transactions across e-commerce platforms and payment apps.</p>`,
    sectionHeading1: `What Is Card Tokenization`,
    sectionDescription1: `<p>Card tokenization is a security process that replaces a customer’s actual card number (PAN) with a randomly generated, unique token during digital payments. This token can be used for transactions instead of storing or sharing sensitive card data, reducing exposure to fraud. In India, tokenization is mandated and regulated by the RBI for all card-on-file transactions across e-commerce platforms and payment apps.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Tokenization protects customers and merchants by preventing the storage of real card numbers on websites, apps, or payment gateways. Instead of handling sensitive credentials, businesses use tokens that have no exploitable value if leaked.</p><p>For organisations, tokenization:</p><p>i. Lowers PCI-DSS handling burden</p><p>ii. Reduces fraud risk in online payments</p><p>iii. Ensures compliance with RBI’s card-on-file guidelines</p><p>iv. Improves customer trust and transaction security</p><p>v. Helps streamline recurring payments and saved-card experiences</p><p>Tokenization is now foundational for digital commerce, subscriptions, and card-based online payments.</p>`,
    sectionHeading3: `How Card Tokenization Works`,
    sectionDescription3: `<p>When a customer opts to save a card or initiates a digital payment:</p><p>1. The customer consents to tokenization on a platform/app.</p><p>2. The card network (Visa, Mastercard, RuPay, Amex) replaces the actual card number with a unique token.</p><p>3. This token is securely stored by the merchant or payment processor.</p><p>4. During payment, the token and a unique cryptogram are used instead of the real PAN.</p><p>5. The card network detokenizes the information in a secure environment to process the transaction.</p><p>The token is domain-restricted, usable only on the merchant/app for which it was generated.</p>`,
  },
  {
    keyword: `Cost of Capital`,
    slug: `cost-of-capital`,
    sheet: `C`,
    definition: `<p>Cost of capital is the rate of return a company must earn to justify the cost of financing its operations, investments, or growth. It represents the minimum return required by shareholders and lenders for providing funds to the business. In simple terms, it is the company’s “hurdle rate” for making financially viable decisions.</p>`,
    sectionHeading1: `What is Cost of Capital`,
    sectionDescription1: `<p>Cost of capital is the rate of return a company must earn to justify the cost of financing its operations, investments, or growth. It represents the minimum return required by shareholders and lenders for providing funds to the business. In simple terms, it is the company’s “hurdle rate” for making financially viable decisions.</p>`,
    sectionHeading2: `Business Context`,
    sectionDescription2: `<p>Every business raises money through equity, debt, or a mix of both. Each source comes with a cost: interest on loans or expected returns demanded by equity investors.</p><p>The cost of capital helps finance teams evaluate whether a project, acquisition, expansion, or long-term investment will generate returns higher than what it costs to fund.</p><p>A lower cost of capital means cheaper financing and more favourable conditions for growth. A higher cost indicates increased risk, tightened credit, or reduced investor confidence.</p><p>CFOs use cost of capital to guide capital budgeting, pricing decisions, long-term planning, and strategic investments.</p>`,
    sectionHeading3: `Types of Cost of Capital`,
    sectionDescription3: `<p>1. Cost of Debt</p><p>The effective interest rate a company pays on its borrowings.</p><p>2. Cost of Equity</p><p>The return expected by shareholders or investors for investing in the business.</p><p>3. Weighted Average Cost of Capital (WACC)</p><p>The blended cost of equity and debt, weighted by their share in the capital structure. Formula:<br>WACC = (E/V × Re) + (D/V × Rd × (1 − Tax Rate))</p>`,
    sectionHeading4: `How Cost of Capital Works`,
    sectionDescription4: `<p>Cost of capital is influenced by:</p><p>1. Interest rates and lending conditions</p><p>2. Market risks and economic environment</p><p>3. Company credit rating and leverage</p><p>4. Business performance and stability</p><p>5. Investor expectations</p><p>6. Tax rates and regulatory changes</p><p>Businesses compare expected project returns (IRR, ROI) against the cost of capital. If the expected return exceeds the cost of capital, the project creates value. If not, it destroys value or increases risk.</p>`,
  },
]
