export { default as groupIcon } from "./groupIcon.png"
export { default as paymentSummary } from "./heroImg.webp"

export { default as stepCardImgOne } from "./stepCardImgOne.webp"
export { default as stepCardImgTwo } from "./stepCardImgTwo.webp"
export { default as stepCardImgThree } from "./stepCardImgThree.webp"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"
export { default as stackCardsixImg } from "./stackCardsixImg.webp"
export { default as stackCardThreeImg } from "./stack-card-three-img.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as stackCardsixIicon } from "./streamlined-reimbursement-icon.svg"
export { default as stackCardThreeIcon } from "./stack-card-three-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
