export { default as officeImg } from "./img/office-img.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as greenArrow } from "./img/green-arrow.svg"
export { default as gradientBg } from "./img/gradient-bg.png"
export { default as cardBg } from "./img/card-bg.png"
export { default as faqBg } from "./img/faq-bg.svg"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"
export { default as approved } from "./img/approved.svg"
export { default as policyIcon } from "./img/policyIcon.svg"

// new images
export { default as clockIcon } from "./img/clockIcon.svg"
export { default as multiCardIcon } from "./img/multi-card.svg"
export { default as realTimeTrakingIcon } from "./img/real-time-traking.svg"
export { default as securityIcon } from "./img/security-icon.svg"
export { default as instantActionImg } from "./img/instantActionImg.webp"
export { default as spendAnalylicsImg } from "./img/spend-analylics.svg"
export { default as motherCardImg } from "./img/meal-card-bg.webp"
export { default as rbiLogo } from "./img/rbi.svg"
export { default as corporateCard } from "./img/corporate-card.svg"
export { default as corporateCardIcon } from "./img/oneClick.svg"
export { default as mealCardImg } from "./img/meal-card.png"
export { default as fuelCardImg } from "./img/fuel-card.svg"
export { default as termsAndConCardImg } from "./img/terms-and-conditon.png"
export { default as virtualCardImg } from "./img/virtual-card.svg"
export { default as purchesCardImg } from "./img/purches-card.svg"
export { default as digitalCardImg } from "./img/digital-marketing-card.svg"
export { default as sassCardImg } from "./img/sass-card.svg"
export { default as payrollCardImg } from "./img/payroll-card.webp"
export { default as fleetCardImg } from "./img/fleet-card.webp"
// .../////
export { default as paymentGatwayImg } from "./img/payment-gateway.png"
export { default as paymentGatwayIcon } from "./img/payment-gateway-icon.svg"
export { default as paymentLinkImg } from "./img/payment-link.png"
export { default as paymentLinkIcon } from "./img/payment-links-icon.svg"
export { default as paymentButtonImg } from "./img/payment-button.png"
export { default as paymentButtonIcon } from "./img/payment-button-icon.svg"
export { default as paymentPageImg } from "./img/payment-page.png"
export { default as paymentPageIcon } from "./img/payment-page-icon.svg"
export { default as upiImg } from "./img/upi.png"
export { default as upiIcon } from "./img/upi-payment-icon.svg"
export { default as qrCodeImg } from "./img/qr-code.png"
export { default as qrCodeIcon } from "./img/qr-code-icon.svg"
export { default as circles } from "./img/Circle 5.svg"
export { default as instantSettelmentIcon } from "./img/instant-settlement.-iconsvg.svg"
export { default as instantSettelmentImg } from "./img/instant-settlement.-Img.webp"
export { default as affordabilityIcon } from "./img/afordability-suits-icon.svg"
export { default as affordabilityImg } from "./img/afordability-suits-img.webp"
export { default as mealCardImage } from "./img/meal-card.webp"
export { default as cardRotatingImage } from "./img/card-roatating.svg"
export { default as podiumImage } from "./img/podium.png"
export { default as heroCardImg } from "./img/hero card.webp"




export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"

export { default as realTimeExpenseIcon } from "./img/real-time-expense-icon.svg"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
