// Card & Product Images
export { default as mealCardImage } from "./img/meal-card.webp"
export { default as instantActionImg } from "./img/instantActionImg.webp"
export { default as heroCardImg } from "./img/hero card.webp"
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as digitalCardImg } from "./img/digital-marketing-card.svg"
export { default as fleetCardImg } from "./img/fleet-card.webp"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as fuelCardImg } from "./img/fuel-card.svg"
export { default as mealCardImg } from "./img/meal-card.png"
export { default as payrollCardImg } from "./img/payroll-card.webp"
export { default as purchesCardImg } from "./img/purches-card.svg"
export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./img/real-time-expense-icon.svg"
export { default as sassCardImg } from "./img/sass-card.svg"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as termsAndConCardImg } from "./img/terms-and-conditon.png"
export { default as wideAcceptanceNetwork } from "./img/wide-acceptance-network.webp"
export { default as wideAcceptanceNetworkIcon } from "./img/wide-acceptance-network-icon.svg"
export { default as iconOne } from "./img/subscribtionIcon.svg"
export { default as iconTwo } from "./img/employeeIcon.svg"
export { default as iconThree } from "./img/vendorIcon.svg"
export { default as iconFour } from "./img/travelExpenceIcon.svg"

// Slider Icons
export { default as sliderOneIcon } from "./img/sliderOneIcon.svg"
export { default as sliderTwoIcon } from "./img/sliderTwoIcon.svg"
export { default as sliderThreeIcon } from "./img/sliderThreeIcon.svg"
export { default as sliderFourIcon } from "./img/sliderFourIcon.svg"
export { default as sliderFiveIcon } from "./img/sliderFiveIcon.svg"

// Step Icons
export { default as firstIcon } from "./img/icon-one.svg"
export { default as secondIcon } from "./img/icon-two.svg"
export { default as thirdIcon } from "./img/icon-three.svg"
export { default as fourthIcon } from "./img/icon-four.svg"
