export { default as officeImg } from "./img/office-img.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as greenArrow } from "./img/green-arrow.svg"
export { default as gradientBg } from "./img/gradient-bg.png"
export { default as cardBg } from "./img/card-bg.png"
export { default as faqBg } from "./img/faq-bg.svg"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"
export { default as approved } from "./img/approved.svg"
export { default as policyIcon } from "./img/policyIcon.svg"

// new images
export { default as clockIcon } from "./img/clockIcon.svg"
export { default as multiCardIcon } from "./img/multi-card.svg"
export { default as realTimeTrakingIcon } from "./img/real-time-traking.svg"
export { default as securityIcon } from "./img/security-icon.svg"
export { default as instantActionImg } from "./img/instant-action-img.svg"
export { default as spendAnalylicsImg } from "./img/spend-analylics.svg"
