export { default as officeImg } from "./office-img.png"
export { default as whiteArrow } from "./white-arrow.png"
export { default as greenArrow } from "./green-arrow.svg"
export { default as gradientBg } from "./gradient-bg.png"
export { default as cardBg } from "./card-bg.png"
export { default as faqBg } from "./ermImg.png"
export { default as heavyLiftingIconOne } from "./heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./heavy-lifting-icon-four.svg"
export { default as creditCard } from "./credit_card.svg"
export { default as blueArrow } from "./blue-arrrow.svg"
export { default as approved } from "./approved.svg"

export { default as motherCardImg } from "./motherCardImg.svg"
export { default as advanceAi } from "./advanceAi.webp"
export { default as receipt } from "./receipt.webp"
export { default as upi } from "./upi.webp"
export { default as walletExpense } from "./walletExpense.webp"

export { default as bannerLottie } from "./lottie/Expense.json"
export { default as itIcon } from "./it-saas-icon.svg"
export { default as ecoomerceIcon } from "./ecoomerce-icon.svg"
export { default as manufactureIcon } from "./manufacture-icon.svg"
export { default as logisticIcon } from "./logistic-icon.svg"
export { default as consultancyIcon } from "./consultancy.svg"
export { default as pharmacyIcon } from "./pharmacy.svg"
export { default as blurImg } from "./blurBg.png"

export { default as smartIconeOne } from "./smartIconOne.svg"
export { default as smartIconeTwo } from "./smartIconTwo.svg"
export { default as smartIconeThree } from "./smartIconThree.svg"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"

export { default as stackCardThreeImg } from "./stack-card-three-img.webp"
export { default as stackCardsixImg } from "./stack-card-six-img.webp"

export { default as realTimeExpenseIcon } from "./real-time-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as stackCardThreeIcon } from "./stack-card-three-icon.svg"
export { default as stackCardsixIicon } from "./stack-card-six-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"
export { default as artboardBg } from "./ArtboardBg.svg"

export { default as whatsappIcon } from "./whatapp.svg"
export { default as mailIcon } from "./mail.svg"
export { default as scannIcon } from "./scanner.svg"
export { default as realTimeIcon } from "./realTime.svg"
export { default as travelIcon } from "./travel.svg"
export { default as autoCalculateIcon } from "./autoCalculate.svg"
export { default as awareIcon } from "./securty.svg"
export { default as integreatedControlIcon } from "./integreatedControl.svg"
export { default as walletlIcon } from "./wallet.svg"
export { default as controlIcon } from "./control.svg"
export { default as trackIcon } from "./track.svg"
export { default as cashIcon } from "./cash.svg"
export { default as taxSaveIcon } from "./taxSave.svg"
export { default as instantAcessIcon } from "./instantAcess.svg"
export { default as verifiedIcon } from "./verified.svg"
export { default as visibilityIcon } from "./visibility.svg"

export { default as corporateCard } from "./coprate-card.png"
export { default as automaticCard } from "./automaticCard.svg"
export { default as gstCard } from "./gst.png"
export { default as expenseCard } from "./expenseCard.svg"
export { default as exchangeCard } from "./exchangeCard.svg"
export { default as trackingCard } from "./tracking.svg"
export { default as disrubsmentCard } from "./disbruesment.svg"
export { default as customExpenseCard } from "./customExpense.svg"

export { default as encruption } from "./encruption.svg"
export { default as complience } from "./complienceIcon.svg"
export { default as audit } from "./auditIcon.svg"
export { default as signOn } from "./sign-on-icon.svg"
export { default as key } from "./key-icon.svg"
export { default as policyIcon } from "./policyIcon.svg"
export { default as bg1 } from "./bg4.jpg"
export { default as bg2 } from "./bg3.jpg"
export { default as bg3 } from "./bg2.jpg"
export { default as bg4 } from "./bg1.jpg"
export { default as bg5 } from "./bg6.jpg"
export { default as bg6 } from "./bg5.jpg"
