export { default as autoCollect } from "./auto-collect.svg"
export { default as instant } from "./instant-settlement.svg"
export { default as paymentButton } from "./pazment-button.svg"
export { default as paymentGateway } from "./payment-gateway.svg"
export { default as paymentLink } from "./payment-link.svg"
export { default as qrCodes } from "./qrCode.svg"
export { default as reminder } from "./remineder-engien.svg"

export { default as paymentLinkImage } from "./payment-link.webp"
export { default as shareImage } from "./shareImg.webp"
export { default as paymentOptionImage } from "./payment-option.webp"
export { default as mealCardImage } from "./collect-payment.webp"
export { default as paymentSummary } from "./heroImg.webp"
export { default as groupIcon } from "./groupIcon copy.svg"

export { default as scrollIconOne } from "./scrollIconOne.svg"
export { default as scrollIconTwo } from "./scrollIconTwo.svg"
export { default as scrollIconThree } from "./scrollIconThree.svg"

export { default as taskIconOne } from "./task-icon-one.svg"
export { default as taskIconTwo } from "./task-icon-two.svg"
export { default as taskIconThree } from "./task-icon-three.svg"
