export { default as twitterLogo } from "./img/twitter.svg";
export { default as linkedinLogo } from "./img/linkedin.png";
export { default as fbLogo } from "./img/fb.png";
export { default as instLogo } from "./img/insta.png";
export { default as call } from "./img/call.png";
export { default as locationPin } from "./img/location-pin.png";
export { default as pci } from "./img/pci.png";
export { default as soc } from "./img/soc.png";
export { default as rbi } from "./img/rbi.png";
