export { default as bannerSlider1 } from "./bannerSlider1.webp"
export { default as bannerSlider2 } from "./bannerSlider2.webp"
export { default as bannerSlider3 } from "./bannerSlider3.webp"
export { default as mobilebannerSlider1 } from "./mobilebannerSlider1.webp"
export { default as mobilebannerSlider2 } from "./mobilebannerSlider2.webp"
export { default as mobilebannerSlider3 } from "./mobilebannerSlider3.webp"
