export { default as groupIcon } from "./img/groupIcon.svg"
export { default as paymentSummary } from "./img/heroImg.webp"
export { default as mealCardImage } from "./img/collect-payment.webp"
export { default as notificationImage } from "./img/notification.webp"
export { default as optimizedIcon } from "./img/website-requierd.webp"
export { default as paymentLinkImage } from "./img/payment-link.webp"
export { default as paymentOptionImage } from "./img/payment-option.webp"
export { default as shareImage } from "./img/shareImg.webp"

export { default as scrollIconOne } from "./img/scrollIconOne.svg"
export { default as scrollIconTwo } from "./img/scrollIconTwo.svg"
export { default as scrollIconThree } from "./img/scrollIconThree.svg"
export { default as scrollIconFour } from "./img/scrollIconFoursvg.svg"

export { default as taskIconOne } from "./img/task-icon-one.svg"
export { default as taskIconTwo } from "./img/task-icon-two.svg"
export { default as taskIconThree } from "./img/task-icon-three.svg"
export { default as taskIconFour } from "./img/task-icon-four.svg"
export { default as taskIconFive } from "./img/task-icon-five.svg"

export { default as crouselIconOne } from "./img/crouselIconOne.svg"
export { default as crouselIconTwo } from "./img/crouselIconTwo.svg"
export { default as crouselIconThree } from "./img/crouselIconThree.svg"
export { default as crouselIconFour } from "./img/crouselIconFour.svg"
export { default as crouselIconFive } from "./img/crouselIconFive.svg"
