export { default as mealCardImg } from "./meal-card.png"
export { default as fuelCardImg } from "./fuel-card.svg"
export { default as termsAndConCardImg } from "./terms-and-conditon.png"
export { default as virtualCardImg } from "./virtual-card.svg"
export { default as purchesCardImg } from "./purches-card.svg"
export { default as sassCardImg } from "./sass-card.svg"
export { default as fleetCardImg } from "./fleet-card.svg"

export { default as heroCardImg } from "./hero card.webp"
export { default as mealCardImage } from "./meal-card.webp"
export { default as instantActionImg } from "./instantActionImg.webp"

export { default as realTimeExpense } from "./real-time-expense.webp"
export { default as fraudProtection } from "./fraud-protection.webp"
export { default as streamlinedReimbursement } from "./streamlined-reimbursement.webp"
export { default as costControlSavings } from "./cost-control-savings.webp"
export { default as wideAcceptanceNetwork } from "./wide-acceptance-network.webp"

export { default as realTimeExpenseIcon } from "./real-time-expense-icon.svg"
export { default as fraudProtectionIcon } from "./fraud-protection-icon.svg"
export { default as streamlinedReimbursementIcon } from "./streamlined-reimbursement-icon.svg"
export { default as costControlSavingsIcon } from "./cost-control-savings-icon.svg"
export { default as wideAcceptanceNetworkIcon } from "./wide-acceptance-network-icon.svg"

export { default as iconOne } from "./predifinedIcon.svg"
export { default as iconTwo } from "./centerlisedIcon.svg"
export { default as iconThree } from "./notificationIcon.svg"
export { default as iconFour } from "./reconcilationIcon.svg"
export { default as iconFive } from "./secureIcon.svg"
export { default as firstIcon } from "./icon-one.svg"
export { default as secondIcon } from "./icon-two.svg"
export { default as thirdIcon } from "./icon-three.svg"
