export { default as laptopScreen } from "./img/laptop-screen.png"
export { default as blueBg } from "./img/laptop-screen.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as faqBg } from "./img/faq-bg.png"
export { default as caraouselBg } from "./img/carousel-bg.png"

export { default as bannerLottie } from "./img/lottie/banner.json"

export { default as stepOne } from "./img/step-one.svg"
export { default as stepTwo } from "./img/step-two.svg"
export { default as stepThree } from "./img/step-three.svg"
export { default as partnerIcon } from "./img/partner-icon.svg"
export { default as grayArrow } from "./img/grayArrow.svg"
export { default as cardBg } from "./img/card-bg.png"
export { default as earnMoreLottie } from "./img/lottie/earnMore.json"
export { default as platform } from "./img/platform.svg"
export { default as plugin } from "./img/pligins.svg"
export { default as language } from "./img/language.svg"
export { default as tick } from "./img/tick-icon.svg"
export { default as supportTeam } from "./img/support-team.svg"
export { default as embbended } from "./img/Embedded.png"
export { default as trust } from "./img/build-trust.svg"
export { default as customer } from "./img/customer.png"
export { default as earn } from "./img/earn-more.svg"
