// previous set
export { default as costControlSavings } from "./img/cost-control-savings.webp"
export { default as costControlSavingsIcon } from "./img/cost-control-savings-icon.svg"
export { default as fleetCardImg } from "./img/fleet-card.svg"
export { default as fraudProtection } from "./img/fraud-protection.webp"
export { default as fraudProtectionIcon } from "./img/fraud-protection-icon.svg"
export { default as fuelCardImg } from "./img/fuel-card.svg"
export { default as purchesCardImg } from "./img/purches-card.svg"
export { default as realTimeExpense } from "./img/real-time-expense.webp"
export { default as realTimeExpenseIcon } from "./img/real-time-icon.svg"
export { default as sassCardImg } from "./img/sass-card.svg"
export { default as streamlinedReimbursement } from "./img/streamlined-reimbursement.webp"
export { default as streamlinedReimbursementIcon } from "./img/streamlined-reimbursement-icon.svg"
export { default as termsAndConCardImg } from "./img/terms-and-conditon.png"
export { default as virtualCardImg } from "./img/virtual-card.svg"
export { default as circles } from "./img/Circle 5.svg"
export { default as mealCardImage } from "./img/meal-card.webp"
export { default as cardRotatingImage } from "./img/card-roatating.svg"
export { default as heroCardImg } from "./img/hero card.webp"
export { default as payrollCardImg } from "./img/payroll-card.webp"

// newly added set
export { default as iconOne } from "./img/auto-collect.svg"
export { default as iconTwo } from "./img/subsccribtion.svg"
export { default as iconThree } from "./img/enach.svg"
export { default as iconFour } from "./img/benifits-icon.svg"
export { default as autoCollect } from "./img/autoCollectImg.webp"
export { default as subscribtion } from "./img/subscribtionImg.webp"
export { default as eNach } from "./img/eNachImg.webp"
export { default as firstIcon } from "./img/icon-one.svg"
export { default as secondIcon } from "./img/icon-two.svg"
export { default as thirdIcon } from "./img/icon-three.svg"
export { default as fourthIcon } from "./img/icon-four.svg"
export { default as benfits } from "./img/fourthIMG.webp"
