export { default as officeImg } from "./img/office-img.png"
export { default as whiteArrow } from "./img/white-arrow.png"
export { default as greenArrow } from "./img/green-arrow.svg"
export { default as gradientBg } from "./img/gradient-bg.png"
export { default as cardBg } from "./img/card-bg.png"
export { default as acceleratedGrowthImg } from "./img/acceleratedGrowthImg.svg"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"
export { default as approved } from "./img/approved.svg"
export { default as policyIcon } from "./img/policyIcon.svg"
export { default as groupIcon } from "./img/groupIcon.svg"
export { default as paymentSummary } from "./img/heroImg.webp"
export { default as integration } from "./img/integration.svg"
export { default as paymenyMethod } from "./img/payment-method.svg"
export { default as rank } from "./img/rank.svg"
export { default as leftHand } from "./img/LEFT HAND.svg"
export { default as support } from "./img/support.svg"
export { default as dashboard } from "./img/dashboard.svg"
export { default as paymentLink } from "./img/payment-link.svg"
export { default as paymentPage } from "./img/payment-page.svg"
export { default as qrCodes } from "./img/qrCode.svg"
export { default as invoices } from "./img/invoices.svg"
export { default as paymentButton } from "./img/pazment-button.svg"
export { default as autoCollect } from "./img/auto-collect.svg"
export { default as instant } from "./img/instant-settlement.svg"
export { default as paymentGatewayImg } from "./img/payment-gateway-img.svg"
export { default as reminder } from "./img/remineder-engien.svg"
// .........

export { default as mealCardImage } from "./img/collect-payment.webp"
export { default as paymentLinkImage } from "./img/payment-link.webp"
export { default as shareImage } from "./img/shareImg.webp"
export { default as paymentOptionImage } from "./img/payment-option.webp"
export { default as notificationImage } from "./img/notification.webp"
export { default as secureImage } from "./img/secure-transition.webp"
export { default as reduceFrauds } from "./img/reduce-frauds.webp"
export { default as optimizedIcon } from "./img/website-requierd.webp"
export { default as hundredPercentIcon } from "./img/100.svg"
export { default as activationIcon } from "./img/activation.svg"
export { default as realTimeIcon } from "./img/real-time.svg"
export { default as greenIcon } from "./img/green-icon.svg"

export { default as scrollIconOne } from "./img/scrollIconOne.svg"
export { default as scrollIconTwo } from "./img/scrollIconTwo.svg"
export { default as scrollIconThree } from "./img/scrollIconThree.svg"
export { default as scrollIconFourth } from "./img/scrolliconFourth.svg"

export { default as taskIconOne } from "./img/task-icon-one.svg"
export { default as taskIconTwo } from "./img/task-icon-two.svg"
export { default as taskIconThree } from "./img/task-icon-three.svg"
export { default as taskIconFour } from "./img/task-icon-four.svg"
export { default as taskIconFive } from "./img/task-icon-five.svg"
export { default as taskIconSix } from "./img/task-icon-six.svg"










// home


export { default as collectPaymentboxIcon1 } from "./img/collect-payment-box-icon-1.svg"
export { default as collectPaymentboxIcon2 } from "./img/collect-payment-box-icon-2.svg"
export { default as collectPaymentboxIcon3 } from "./img/collect-payment-box-icon-3.svg"
export { default as collectPaymentboxIcon4 } from "./img/collect-payment-box-icon-4.svg"
export { default as collectPaymentboxIcon5 } from "./img/collect-payment-box-icon-5.svg"
export { default as collectPaymentboxIcon6 } from "./img/collect-payment-box-icon-6.svg"
export { default as makePayment1 } from "./img/makePayment-1.webp"
export { default as makePayment2 } from "./img/makePayment-2.webp"
export { default as makePayment3 } from "./img/makePayment-3.webp"
export { default as makePayment4 } from "./img/makePayment-4.webp"
export { default as prepaidTop1 } from "./img/prepaidTop1.svg"
export { default as prepaidTop2 } from "./img/prepaidTop2.svg"
export { default as prepaidTop3 } from "./img/prepaidTop3.svg"
export { default as prepaidTop4 } from "./img/prepaidTop4.svg"
export { default as prepaidTop5 } from "./img/prepaidTop5.svg"
export { default as prepaidBottom1 } from "./img/prepaidBottom1.svg"
export { default as prepaidBottom2 } from "./img/prepaidBottom2.svg"
export { default as rewardImg1 } from "./img/reward_img1.webp"
export { default as rewardImg2 } from "./img/reward_img2.webp"
export { default as rewardImg3 } from "./img/reward_img3.webp"
export { default as rewardIcon } from "./img/reward_icon.svg"
export { default as rewardSliderIcon1 } from "./img/reward_slider_icon1.svg"
export { default as rewardSliderIcon2 } from "./img/reward_slider_icon2.svg"
export { default as rewardSliderIcon3 } from "./img/reward_slider_icon3.svg"
export { default as rewardSliderIcon4 } from "./img/reward_slider_icon4.svg"
export { default as rewardSliderIcon5 } from "./img/reward_slider_icon5.svg"
export { default as receivableBottomIcon } from "./img/receivable_bottom_icon.svg"
export { default as bankIcons } from "./img/bankIcons.svg"
export { default as bankIcons2 } from "./img/bankIcons2.svg"
export { default as AdiadsBg } from "./img/adidas_bg.webp"
export { default as Adiadslogo } from "./img/adidas_icon.svg"
export { default as AdiadsProfile } from "./img/adidas.png"
export { default as delMonteBg } from "./img/digital_bg.webp"
export { default as delMontelogo } from "./img/delMonte.svg"
export { default as delMonteProfile } from "./img/delMonte.png"
export { default as bigBg } from "./img/big_bg.webp"
export { default as biglogo } from "./img/big.svg"
export { default as bigProfile } from "./img/big.png"
export { default as vianetBg } from "./img/vianet.webp"
export { default as vianetBackLogo } from "./img/vianet_color.png"
export { default as vianetProfile } from "./img/vianet.png"
export { default as vianetlogo } from "./img/vianet_white.png"
export { default as honeycombBg } from "./img/honeycomb.webp"
export { default as honeycomblogo } from "./img/honeycomb.svg"
export { default as honeycombProfile } from "./img/hon.png"
export { default as securityIcon1 } from "./img/security_icon1.svg"
export { default as securityIcon2 } from "./img/security_icon2.png"
export { default as securityIcon3 } from "./img/security_icon3.png"
export { default as securityIcon4 } from "./img/security_icon4.png"
export { default as securityIcon5 } from "./img/security_icon5.png"
export { default as BuiltforBuildersCardIcon } from "./img/BuiltforBuildersCardIcon.svg"
export { default as BuiltforBuildersCardIcon2 } from "./img/BuiltforBuildersCardIcon2.svg"
export { default as BuiltforBuildersCardIcon3 } from "./img/BuiltforBuildersCardIcon3.svg"