export { default as whiteArrow } from "./img/white-arrow.png"
export { default as groupIcon } from "./img/groupIcon.png"
export { default as paymentSummary } from "./img/heroImg.webp"
export { default as acceleratedGrowthImg } from "./img/acceleratedGrowthImg.svg"
export { default as heavyLiftingIconOne } from "./img/heavy-lifting-icon-one.svg"
export { default as heavyLiftingIconTwo } from "./img/heavy-lifting-icon-two.svg"
export { default as heavyLiftingIconThree } from "./img/heavy-lifting-icon-three.svg"
export { default as heavyLiftingIconFour } from "./img/heavy-lifting-icon-four.svg"
export { default as creditCard } from "./img/credit_card.svg"
export { default as blueArrow } from "./img/blue-arrrow.svg"

export { default as paymentButton } from "./img/pazment-button.svg"
export { default as mealCardImg } from "./img/meal-card.png"
export { default as fuelCardImg } from "./img/fuel-card.svg"

export { default as instant } from "./img/instant-settlement.svg"
export { default as reminder } from "./img/remineder-engien.svg"
export { default as paymentGateway } from "./img/payment-gateway.svg"
// .........

export { default as mealCardImage } from "./img/collect-payment.webp"
export { default as paymentLinkImage } from "./img/payment-link.webp"
export { default as shareImage } from "./img/shareImg.webp"
export { default as paymentOptionImage } from "./img/payment-option.webp"
export { default as notificationImage } from "./img/notification.webp"
export { default as secureImage } from "./img/secure-transition.webp"
export { default as optimizedIcon } from "./img/website-requierd.webp"
export { default as hundredPercentIcon } from "./img/100%.svg"
export { default as activationIcon } from "./img/activation.svg"
export { default as realTimeIcon } from "./img/real-time.svg"

export { default as scrollIconOne } from "./img/scrollIconOne.svg"
export { default as scrollIconTwo } from "./img/scrollIconTwo.svg"
export { default as scrollIconThree } from "./img/scrollIconThree.svg"
export { default as scrollIconFour } from "./img/scrollIconFoursvg.svg"

export { default as taskIconOne } from "./img/task-icon-one.svg"
export { default as taskIconTwo } from "./img/task-icon-two.svg"
export { default as taskIconThree } from "./img/task-icon-three.svg"
export { default as taskIconFour } from "./img/task-icon-four.svg"
export { default as taskIconFive } from "./img/task-icon-five.svg"
export { default as taskIconSix } from "./img/task-icon-six.svg"
export { default as faqBg } from "./img/secondFaq.webp"
